### ISSUE TITLE
招聘PHPer - 云南滇商集团股份有限公司

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#10]
工作地点：云南省昆明市滇池路南亚风情第壹城B座1501

请联系：解(xiè)老师 focusspeed@gmail.com

先写福利：
- 男女比例 1:3 ！！！
- 5险1金
- 工资之外还有项目奖金
- leader帮买早点
## 初级职位(4-6k)

职位描述:
1，了解linux服务器及php相关部署
2，熟悉mysql数据库
3，精通php程序语言，有一定的面向对象编程基础
4，熟悉javascript，了解一些框架如angular,vuejs等。
5，能使用php编写restful api。
6，熟悉php框架，如yii，thinkphp。

任职要求：
1，能够完成安排的一些后台模块及API编写。
2，能够使用javascript编写后台管理端页面。

**Comment by ghost** [comment]
### 高级职位(6k-12k)

岗位职责：
1，三年以上PHP+MYSQL开发经验，熟悉php开发，能够独立开发网站；
2，熟练使用mysql，对mysql性能调优有一定了解；
3，熟悉linux环境下的apache+php+mysql的配置及管理；
4，熟悉javascript，html，css等。
5，能够编写restful API。
6，具有优良的编程风格和习惯，有丰富的项目开发经验，富有团队精神和敬业精神；
7，性格开朗，良好的表达和沟通能力，思路清晰，较强的责任心、团队精神；

加分项：
1，有使用过php框架如Yii，thinkPHP。
2，有开发过企业相关应用。
3，对性能优化有所了解

任职要求：
1、根据需求独立进行项目的程序架构分析、数据库规则；
2，能够搭建好后台框架，编写后台模块及API编写。
3，能够使用javascript编写后台管理端页面。

**Comment by ZhangRGK** [comment]
以下是福利的部分。

- 男女比例 1:3
- 5险1金
- 项目奖金
- leader帮买早点
