### ISSUE TITLE
EMQ Open Day 005｜在春之城拥抱开源 ｜ 邀请函

### ISSUE THREAD

**Issue by ysfscream** [yncoder/yncoder.github.io#100]
**摘要**：开源的世界永远都是春天

提到昆明，你会想到什么？是四季如春的宜人气候，还是一年一度造访滇池的海鸥？

对于 EMQ 来说，这里不仅出现了 [MQTT X](https://mqttx.app/zh) 这样用于服务 MQTT Broker 开发者和使用者的开源项目，作为 EMQ 研发团队的所在地之一，这里也聚集了很多热爱开源热爱技术的优秀工程师。

我们一直认为，开源与先进技术不是一线城市的专属，我们也相信在昆明，会有许多积极开放的开源爱好者和才华横溢、乐于分享的程序员。

时值 EMQ 昆明新 Office 落成，新一期 EMQ Open Day，我们邀请大家来昆明玩！一起在春城拥抱开源！

**主题**：Open Source in Kunming （开源在昆明）

**时间**：2021/06/05  14:00～16:00

**地点**：昆明市五华区学府路745号海伦先生1栋1813室

**议程**：

- 关于开源：开源的发展，如何参与开源项目，如何开发和维护开源项目，以及对开源未来的期待
- 关于 MQTT X：MQTT X 是 EMQ 开源的一款跨平台 MQTT 5.0 桌面客户端工具。我们将为大家介绍这一开源项目的发展历程及简单使用教程，并分享未来的一些功能规划
- 自由交流：一起寻找在昆明热爱开源与技术的同好者！

**嘉宾**：余仕帆，EMQ 研发工程师，MQTT X 的开发者和维护者

EMQ Open Day 发起的初衷，就是为大家提供技术交流、思想碰撞的平台，让大家通过 EMQ 结识更多有共同热爱、可以彼此学习的伙伴。后续我们也会陆续在更多城市的 EMQ Office 举办 Open Day，将开源之风吹向各地，让领先技术与开放思想的种子生根发芽。

活动报名地址：https://6063343408062.huodongxing.com/event/7599815731500

也可以直接在评论区留言报名，无限零食饮料，宽敞自由舒适的交流地点。欢迎各位“开花者”前来交流，让各位身在昆明的开发者不再“孤独”。

**Comment by oceanlvr** [comment]
👏 👏 👏 👏 👏  好耶！

**Comment by kerrysheng** [comment]
这工具用过，非常好用，期待见到作者和大佬们

**Comment by lixujia** [comment]
当前项目正在用EMQ

**Comment by ysfscream** [comment]
> 当前项目正在用EMQ

哇！有问题可以直接过来交流呀

**Comment by lixujia** [comment]
> > 当前项目正在用EMQ
> 
> 哇！有问题可以直接过来交流呀

有疑问时过来请教，还请多多关照！

**Comment by kentzhang-geek** [comment]
用过，相当赞，用阿里云按量付费测试了百万并发，后来用在公司项目上。
那时候还有个想法，用fpga来实现mqtt协议栈，然后万兆SFP+来几个，看看能不能大幅提高msg转发率，这样就成了物联网基础设施了，不过仅停留在“想”。后来搞图形学就不在这个方向了。
