### ISSUE TITLE
开源项目招聘系统工程师

### ISSUE THREAD

**Issue by sanlee42** [yncoder/yncoder.github.io#101]
#### 项目介绍
0. [Github](https://github.com/starcoinorg/starcoin)
1. [Official website](https://starcoin.org/en)
2. [Twitter](https://twitter.com/starcoinstc)
3. [Discord](https://discord.gg/qFJTGKM7vK)

#### 系统开发工程师
参与公链基础系统的开发与优化。包括但不局限区块链网络，存储等底层优化，合约基础库开发等。开发语言 Rust，或者愿意转 Rust 的 C++/Java/Go 工程师。

#### 任职要求
1. 熟悉 Rust 或者 C++/Java/Go。
2. 有存储，网络基础设施开发经验者优先。
3. 有公链系统开发经验者优先。

#### 薪资待遇

1. Base： 20k-60k *14
2. 一周40小时, 可 Remote.

#### 联系方式
458041958@qq.com

**Comment by AdorableGhost** [comment]
是在昆明工作吗？
