### ISSUE TITLE
成都智意数字科技有限公司招聘开发工程师 / 需求工程师 / 售前工程师

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#102]
集团公司主页: https://www.troy.cn/

入职成都智意数字科技有限公司.

社保可以选择缴在成都或者昆明.

补充了需要招聘角色:

## 售前工程师岗位

1. 负责组织制定项目的技术方案编写、标书的准备、讲解及用户答疑等工作；
2. 配合区域销售完成与用户的技术（或解决方案）交流、方案宣讲及系统演示工作；
3. 行业解决方案编写、内部推广培训、方案改进及技术协调等；
4. 配合做好与合作伙伴厂商的技术交流；
5. 有智慧城市、智慧医疗行业拓展经验优先；

待遇 1w-2w, 这个岗位就不考虑刚入门的人了, 有经验的人可以考虑

## 实施工程师/需求工程师

1. 负责项目的需求分析、方案设计、系统集成、测试、验收、培训等工作；
2. 负责项目的技术交流、方案宣讲及系统演示工作；
3. 负责项目的技术支持、问题解决、系统维护等工作；
4. 负责项目的技术文档编写、技术培训、技术协调等工作；

## 开发工程师

目前还有 2 名额, 希望有妹子加入, 目前团队全是帅哥, 阳刚气实在太足了.

参与开发写代码为主, 可以接受刚入门人员, 但不能完全空白对软件开发一点经验都没有, 技术栈和细节在下面详述了.

### 待遇:

毕业刚入门的 5k-8k, 能力高经验丰富者也很难突破 1.5w. 我会想办法从其他的项目中提高团队成员收入, 根据个人对金钱的渴望, 可卷可闲.

### 目标:

技术的提升主要用于怎么样用更少的时间精力, 来完成实现政府企业的 CRUD 项目(没办法, 云南就是这些项目多), 再积累库和成熟解决方案减少开发成本, 特定行业有可能往行业产品方向走. 目标为了是轻松不加班又能惬意的挣到钱.

### 技术:

前端工作会比较多, 可能是 React 系, 毕竟 AntD 很适合 CRUD 后台管理项目; 小程序 Taro; APP 也许会用 Flutter 但很少有项目会要开发 APP; 偏向无后端的方案 SupaBase, Hasura, LeanCloud, CloudBase 等, 接口会是 GraphQL; 数据库大概以 PostgreSQL 为主; serverless 和云厂商提供的现成产品, 低代码等能省开发成本的产品可能都会用.

常用数据库 MySQL, Oracle, PostgreSQL 相关工作也会有, SQL 的估计用的不少, 熟悉 SQL 程度越高越好. 目前稳定的项目是医保的数据域, 数据整合工作多. Java Python GoLang 还不确定会不会用到.

以上技术不要求都会, 契合度度高肯定自己也舒服, 但哪怕刚入门愿意学的可以都试试. 沟通能力较强的也可以试试需求工程师的角色......

### 其他情况:

上班地点在万达双塔附近的金地中心, 高档写字楼, 旁边星巴克, 各种好吃好喝, 健身房等一应俱全, 美女网红聚集出现频率很高, 貌似因为有几家模特经纪公司.

### 待遇, 福利及其他:(8 月 18 日补充)

核心项目是医保的, 经费充足, 稳定性高, 虽然是初创团队, 但已经是很稳初创了. 画个饼: 早期加入利益和未来收益可能会更大.

根据来面试的朋友关心的点, 逐步确认了解的情况来补充:

- 五险：社保缴纳基数为全额薪酬的 40%（低于当地最低薪酬的按照最低薪酬缴纳），当月 15 号之前缴纳当月社保，15 号后缴纳次月社保，入职当天需提供身份证扫描件.
- 公积金：转正后（试用期 3 个月）缴纳公积金，缴纳额为全额薪酬的 9%
- 商业补充医疗：入职次月生效
- 工作电脑需要自备, 每年一次性发 1680 电脑使用补助, 发 3 年.
- 原则每年 14 薪, 需要看表现打分, 太差有可能只拿到 12 薪
- 午餐补助工作日每天 10 块, 每个月大概能拿到 200 多块. 出差这个钱就没了
- 油补(需备案, 满足条件名下有车&个人有驾照)
- 通话补助：150 元/月(转正之后享受)
- 出差补助根据出差地, 省外 150 每天, 省内 130 每天. 住宿实报实销(有上限), 不与这个费用牵扯
- 出差高铁可坐一等座
- 节日福利：法定节假日实物礼品+生日积分兑换+特殊节日(六一、三八等)
- 带薪假期：入职当年度即可享受（按照劳动合同法折算标准）+法定节假日+双休
- 每年组织省外旅游
- 不定期的团建聚会活动

### 联系方式

加我微信: bigzhu

**Comment by bigzhu** [comment]
一些额外的情况, 福利待遇什么, 我会根据确认来逐步补充进去.

**Comment by bigzhu** [comment]
已经有8个帅哥了, 真的帅.. 是不是该来点姑娘. 不然我担心他们开始搞基.

**Comment by szy0syz** [comment]
就本地市场而言，福利待遇很不错嘛
帮顶 🤠

**Comment by hsiong** [comment]
帮顶 ~  6险1金 + 各种福利 ~ ❤️了❤️了 ~ 

期待有 java 或者 golang 的需求 ~

**Comment by bigzhu** [comment]
> 帮顶 ~ 6险1金 + 各种福利 ~ ❤️了❤️了 ~
> 
> 期待有 java 或者 golang 的需求 ~

其实我没那么严格的要求技术栈, 我也不觉得程序员非要和哪种技术栈卡死...有兴趣都可以试试, 哪怕现在招的差不多了

**Comment by bigzhu** [comment]
暂时招的也差不多了, 但应该长期都有少量名额给合适的人的. 
有意向的人可以继续加我聊聊. 合作机会都有.
我就先关闭了

**Comment by bigzhu** [comment]
继续招聘, 能来个妹子就好了, 清一色汉子, 阳气实在太重了

**Comment by bigzhu** [comment]
名额用完了, 关闭招聘.

全部是汉子, 悲哀的故事
