### ISSUE TITLE
锤子科技SmartisanT2发布会集中观看活动

### ISSUE THREAD

**Issue by samyn** [yncoder/yncoder.github.io#12]
一起围观中国最有争议的互联网创业者倒霉蛋老罗的表演
![77ba84dfjw1ezf59sj043j20og191adp](https://cloud.githubusercontent.com/assets/4281269/12018048/0f2e83a2-ad99-11e5-9c22-f8bb2319b890.jpg)
地点：日新中路399号广福城A11-3栋十一层房星-黑客咖啡
时间：2015年12月29日19：30-21：30
免费提供小食、啤酒，欢迎参加。但考虑到准备工作的难度，报名者需要在29日下午5点前电话预约，在获得确认后再前往。

联系人：Sam哥 电话：13577062070

**Comment by gc87** [comment]
:tada: :balloon:

**Comment by Vanessa219** [comment]
:coffee: 居然对外嘢

**Comment by samyn** [comment]
是呀，可惜没人感冒

张锡 Zhang Xi 

发件人： Vanesssa
发送时间： 2016-01-22 09:16
收件人： yncoder/yncoder.github.io
抄送： samyn
主题： Re: [yncoder.github.io] 锤子科技SmartisanT2发布会集中观看活动 (#12)
居然对外嘢
