### ISSUE TITLE
周末（2016 年 1 月 16 日）长虫山小走

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#13]
计划走一个不超过 10km 的小徒步路线，长虫山是昆明龙脉，登顶可观昆明全景，难度不大。
## 集合
- 时间：2016 年 1 月 16 日早 8:00
- 地点：TODO
- 天气预报：晴 2-16 度
## 物资装备
- 小背包（建议）
- 水至少 1L（必须）
- 零食或能量食品若干（必须）
- 运动鞋或登山鞋（必须）
- 防风保暖外套（建议）
- 登山杖*2（建议）
- 魔术头巾（建议）
- 帽子/墨镜（建议）
## 报名

跟帖确认报名。
## 免责声明

本次活动为非商业化自助户外活动。户外运动有一定的危险性和不可预知性。参加者对自己的行为及后果负完全责任。领队组除接受大家监督、有责任控制费用和公开帐目外，不对任何由户外运动本身具有的风险以及往返路途中发生的危险所产生的后果负责。凡参加者均视为具有完全民事行为能力人。如在活动中发生人身损害后果，赔偿责任领队组不承担，由受损害人依据法律规定和本声明依法解决。

如有需要请尽早在网上购买保险。

**Comment by williamwa** [comment]
报名

**Comment by gc87** [comment]
报

**Comment by Annieeei** [comment]
报～

**Comment by bigzhu** [comment]
报，问题去哪集合？（去不了了，临时工作上又有事）

**Comment by mytharcher** [comment]
因封山小队改道参观了昆明湖人工瀑布公园。
