### ISSUE TITLE
小型聚会（2016年1月23日）春节前最后一次面基

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#16]
快过春节了，马上拿年终奖了，程序员不安分的心开始骚动了。离职的、开公司创业的、跳槽的；挖人的、被人挖的都开始有点蠢蠢欲动了。似乎马上又要开始风起云涌了，所以先预热下
# 小型聚会说明

除了有主题的大型聚会外，会很随意的、频繁的时不时召集小型聚会，有以下特点：
- 不一定有特定主题，大家随意吹散牛，碰撞思路为主，挖人的，谈项目合作的请随意
- 以增加基友熟悉度为目标
- 发生的费用参与者自行解决（停车费，车船费，咖啡厅饮品费等）
# 时间

2016年1月23日中午2点开始（忘记周六会下雪了，来的都是真爱！）
# 地点

暂时定为龟龙湖公园[漫咖啡](http://map.baidu.com/?shareurl=1&poiShareUid=3bab0e38062ec8ccc0364485)
# 报名

跟帖报名，达不到2人则默认取消

**Comment by scriptfans** [comment]
先报名吧，如果没有突发情况……

**Comment by allenzhong** [comment]
一般都没问题，只要毛下雪把路给封了

**Comment by bigzhu** [comment]
报，地点我很近

**Comment by zzdjk6** [comment]
报名～

**Comment by xdliuyong** [comment]
跟帖报名。

**Comment by danielliao11** [comment]
没意外是会来的

**Comment by LiuWei-Luke** [comment]
江岸旁边么？报名，新人来听大牛吹逼

**Comment by oldrev** [comment]
报名报名

**Comment by soooooot** [comment]
跟贴报名凑热闹
