### ISSUE TITLE
有多少人在用 Github Pages 托管自己的网站？

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#17]
主要是为了调查下，但同时也是 show 博客地址的机会啊，我先来：http://yanjunyi.com/ （虽然许久没更新）

**Comment by YuYanDev** [comment]
啦啦啦，我也来安利了～，虽然没放在github page上 https://hto.io   ヾ(≧∇≦*)ゝ

**Comment by hsllany** [comment]
有的，我们公司的博客就是在这个上面http://blog.ubirouting.com

**Comment by MrGlory** [comment]
我是打酱油的  
http://www.chuckyang.com/

**Comment by kentzhang-geek** [comment]
我的这个

[http://0871087123.github.io/](http://0871087123.github.io/)

虽然基本不咋用，完全不会web只会C/C++表示不会玩啥好看的
