### ISSUE TITLE
昆明龙慧科技有限公司 招聘软件工程师

### ISSUE THREAD

**Issue by gc87** [yncoder/yncoder.github.io#18]
公司：昆明龙慧科技有限公司
地址：昆明市二环西路625号云铜科技园工程技术中心B座5楼
电话：0871-65373719-8022
公司网址： http://www.lonhwin.com/
新岗位：
## C#开发工程师

岗位职责： 
1、负责公司.net c#项目的开发；
2、对客户需求有较强的理解力、分析能力、提炼能力，能抓住客户的意图来设计程序；
3、对软件产品有较强的操作认识、能根据使用群体不断优化设计、提高用户认可度；
4、有严谨的代码编写能力。

任职资格： 
1、统招本科及以上学历，计算机相关专业优先。
2、二年以上的.net C#开发经验。
3、了解面向对象思想，有良好的代码编写习惯；
4、有GIS相关开发经验者优先。
5、有良好的表达能力和沟通能力，思维清晰，熟悉软件开发流程，设计模式。

薪资待遇
试用期：
试用期1~3个月，待遇2500元~6000元/每月， 根据工作经验，个人能力确定试用期工资。
转正后待遇
工资待遇：3000.00~10000.00/月，根据试用结果而定。
购买五险一金

---
## 安卓开发工程师/IOS开发工程师

岗位职责： 
1、负责公司手机端软件的开发，包括安卓/IOS系统；
2、对客户需求有较强的理解力、分析能力、提炼能力，能抓住客户的意图来实现前端界面设计；
3、对软件产品有较强的操作认识、能根据使用群体不断优化设计、提高用户认可度；
4、有优秀的排版能力和配色能力，一定的创意能力和美工能力。
5、有严谨的代码编写能力，手机端能保证稳定，高效。

任职资格： 
1、统招大专及以上学历，计算机、美术、平面设计、广告设计、多媒体等相关专业优先。
2、有相关工作经验，必须有开发过2个以上的项目经验。
3、熟悉android或IOS系统框架，能进行phone，sms，mms，contact，email，music，camera，GPS，重力感应等应用开发；
4、有GIS相关开发经验者优先。
5、有良好的表达能力和沟通能力，思维清晰，熟悉软件开发流程，设计模式。

薪资待遇

试用期1~3个月，待遇2500元~6000元/每月， 根据工作经验，个人能力确定试用期工资。

转正后待遇

工资待遇：3000.00~10000.00/月，根据试用结果而定。

购买五险一金
## JAVA高级工程师

岗位职责：
1. 从事应用软件核心模块的设计与开发； 
2. 具有规范化,标准化的代码编写习惯和良好的技术文档习惯； 
3. 能辅助项目经理建立完善、规范的软件开发流程和高品质的管理体系并参照执行，保证软件产品的质量和进度，定期提交项目分析报告。 
4. 完成应用软件的子系统或模块设计开发，并撰写概要设计说明书； 
5. 能对程序员进行辅导，检查程序员代码规范和质量； 
6. 具有项目管理的经验者优先。 

任职条件 ：
1. 精通JAVA，掌握OO分析设计思想和设计方法，有良好的编程风格； 
2. 精通J2ee，B/S三层架构，熟练使用常用的开源框架； 
3. 具备良好的系统设计能力； 
4. 熟练掌握SQL Server，Oracle、MySql三种数据库之一； 
5. 熟练掌握常用的XML/Web Service等相关技术； 
6. 5年以上JAVA项目开发经验，其中2个及以上为大型软件项目； 
7. 有责任心，良好的沟通协调能力，团队合作精神，具备良好的学习能力； 
8. 熟悉ActiveMQ/JBossEsb等消息中间件优先； 
9. 做过基于FLASH Builder的界面开发者优先； 
10. 快速学习能力及独立分析解决问题的能力； 
11. 良好的口头沟通能力，能指导程序员； 
12.有水利行业相关开发经验者优先。 
职位要求: 
要求做事有激情 能吃苦耐劳，为人实在，品行善良可靠，责任心强，有一定沟通能力； 
可长期稳定工作，短期打工、频繁跳槽者勿扰； 
待遇 
1、试用期 

试用期1~3个月，待遇2500元~6000元/每月， 根据工作经验，个人能力确定试用期工资。
转正后待遇：
工资待遇：3000.00~10000.00/月，根据试用结果而定。
购买五险一金

---
## UI设计师

岗位职责： 
1、负责公司产品或软件项目的前端设计（软件、网站、手机端）；
2、对客户需求有较强的理解力、分析能力、提炼能力，能抓住客户的意图来实现前端界面设计；
3、对软件产品有较强的操作认识、能根据使用群体不断优化设计、提高用户认可度；
4、有优秀的排版能力和配色能力，一定的创意能力和美工能力。

任职资格： 
1、统招大专及以上学历，计算机、美术、平面设计、广告设计、多媒体等相关专业优先。
2、有相关工作经验，能提供设计作品或画面原型者优先。
3、熟悉Photoshop，Flash，Dreamweaver，Illustrator或其他设计制作软件。
4、有良好的表达能力和沟通能力，思维清晰，熟悉软件开发流程，能配合开发工程师完成开发任务。

薪资待遇
试用期：
试用期1~3个月，待遇1500元~4000元/每月， 根据工作经验，个人能力确定试用期工资。
转正后待遇
工资待遇：2500.00~8000.00/月，根据试用结果而定。
购买五险一金

**Comment by danielliao11** [comment]
纯哥开始招人了么

**Comment by zkg642** [comment]
这都能打广告
