### ISSUE TITLE
昆明怡美假日诚聘——PHP && JAVA开发人员

### ISSUE THREAD

**Issue by SpinFreeze** [yncoder/yncoder.github.io#19]
**PHP开发工程师**

**工作职责范围**

1、负责相关网站系统的技术开发工作；
2、进行业务日志分析，给产品部分提供数据支持；
3、负责接口的开发维护和调试；
4、网站应用和功能模块的设计与程序开发.单元测试.维护文档的编定；
5、电商类产品新功能技术调研和原型快速上线。
**能力要求（招聘）**
1、3~5年Web、wap开发经验，精通PHP面向对象的设计方法，理解MVC模式及SOA思想并能运用在开发中；
2、 精通PHP微信接口开发，并至少使用PHP开发过一个以上大中型项目，能够独立编写中等规模PHP应用程序，有shopnc开发经验者优先考虑；
3、熟练使用thinkPHP、JQuery、Mysql、Oracle等主流关系型数据库、熟悉Redis、Memacher、等缓存服务器、具有大并发开发经验；
4、能熟练使用Linux，拥有查询优化和存储优化经验以及PHP缓存；
5、 责任心强，具有良好的沟通.协作能力和团队合作意识，能够承担重要任务承受较强工作压力。

**薪资**
7K-10K

**Java开发工程师**
**工作职责范围**
1.依据需求文档，负责相关系统和产品的研发工作；
2.根据开发规范撰写开发文档；
3.根据系统开发需求进行技术调研，并进行系统技术架构设计；
4、良好的逻辑思维、沟通和团队协作能力，富有激情、积极主动、关注细节。

**能力要求（招聘）**
 1、3~5年Java Web后台开发经验，熟练使用spring、Hibernate/Mybatis、Structs2 等开源框架；
 2、熟悉分布式、多线程、缓存、消息等高性能架构相关开发技术，具有Maven 开发检验；
 3、熟练使用javascript、Ajax、JQuery等前台框架；
 4、熟练使用zookeper，dubbo分布式框架，熟悉分布式、多线程、缓存、消息等高性能架构相关开发技术；
 5、至少熟练运用Apache、WebLogic、JBoss、WebSphere等一种或两种运行服务器；
 熟练使用mysql和oracle数据库，能够熟练的运用sql
 6、有大数据量处理经验者优先考虑。

**薪资**
7K-10K

联系方式:
- QQ:562920332  
- 周鲜森:13888806937

*_公司介绍 *_
怡美假日旅游集团 诺仕达旗下产业。公司主营业务旅游 酒店 精油.
团队主要开发 商城、ERP、分销系统  提供团队内部使用。

**Comment by codingyangxb** [comment]
大家支持下

**Comment by bigzhu** [comment]
周鲜森？ 这名字好有特点

**Comment by SpinFreeze** [comment]
我们项目经理联系方式    周先生

**Comment by mytharcher** [comment]
没有公司简介么？主要做什么业务最好也说明下呗。

**Comment by danielliao11** [comment]
感觉像是做旅游的……

**Comment by SpinFreeze** [comment]
有意向QQ细聊
公司有传统业务作为背景支撑
主要按内公司内部需求提供定制开发如ERP,分销系统,酒店订票,旅游定制之类
鉴于大家 对开发商城深恶痛绝这里就不写了

**Comment by xiao-hongliang** [comment]
工作地点没有添出来，今日接到一个猎头的电话，说是怡美集团的，不知道是不是你们公司。
