### ISSUE TITLE
2015清明澄江骑行活动召集

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#2]
打算清明后两天（5日，6日）澄江骑行环湖，锻炼下在代码面前窝了一个冬天的身体，感受春天好时光。

抚仙湖周长 93km，骑行正常速度大概要 5-6 小时左右。所以计划 5 日早 8:00 左右开车出发，到禄充-黄金海岸沿线先找好安顿的地方，再开始骑行。早餐自己解决，中午各自用路餐，下午 4:00 左右正常完成的回到安顿的农家休整，准备晚饭，晚上宿农家，可各自扯淡喝酒聊天，当然你也可以带上本子出来写代码。

6 日睡个懒觉起来，有闲心的下湖游泳，中午在农家吃完饭即返昆明各找各妈。

有兴趣的可以跟帖报名，下周五前确定人数分配车辆及更多细节。

活动发起人不承担任何责任，报名参加请对自己的行为和安全负责。

**Comment by williamwa** [comment]
要考虑一个情况，清明几天，出入城的路会比较拥堵。
另外，有没有可能1天搞定。

**Comment by mytharcher** [comment]
是的，就看大家能不能起早了，更早出发当然更好。1天搞定也不是不可以，关键是往返太累，好不容易放个假轻松一点不是很好？

**Comment by danielliao11** [comment]
可惜了，清明回丈母娘家……

**Comment by williamwa** [comment]
另外，自行车用小车拉去？能不能放得下？

**Comment by mytharcher** [comment]
没问题的，两箱福克斯都能装两辆大车。

**Comment by ghost** [comment]
先报名。可能会因为加班缺席……不好意思。

自备自行车，可以开车再带4个人~

**Comment by mytharcher** [comment]
放鸽子的人太多，骑车活动改期再 reopen。

**Comment by mytharcher** [comment]
改约五一，继续走起！

**Comment by ghost** [comment]
我报，我希望是前两天。最后一天发一下烧好上班。
