### ISSUE TITLE
互联网＋法律  招聘 ——Python or Clojure or Js 开发人员

### ISSUE THREAD

**Issue by arlicle** [yncoder/yncoder.github.io#20]
# 关于律品

律品是成立在北京，目前团队在昆明。想通过互联网技术手段为全国的人提供法律服务。真正做到每一个老百姓都用得起的法律服务。我们已经拿到300万的天使轮，目前开始进行PreA轮的融资。目前团队很小，只有两种人程序猿和法律人，有20多个人，但是只有两名技术，有很多的发展空间和学习的机会。技术开发目前我一个技术在昆明，另外一个技术在印度班加罗尔（这几天在以色列。。。），目前产品已经面向用户测试和使用，需要更多的小伙伴加入进来一起完善和改进。我们虽然工作在昆明，但是提供北上广的薪酬待遇。（期权啥的扯太远了，我们直接先来点实际的。）

我是公司的创始合伙人，我做了将近10年的开发，PHP＋Python，自己写过开发框架。喜欢敲敲代码和跑步，自己觉得公司正站在革命一个行业的风口，当你每天看到自己的产品帮助了全国好几万人解决了他们的痛点，收到全国各地人的感谢，你会每天工作都很高兴。帮助每一个老百姓真正打得起官司。
## 公司福利

基础：
1. 五险一金
2. 午餐、晚餐
3. 水果、零食、茶点
4. 合作愉快了 慢慢的可以远程工作，边旅行边工作。我时不时就是这样的，忽然晚上买一个第二天去泰国的机票，然后第二天下午就在清迈过泼水节，骑着大象敲代码了。

硬件配备：MacBook Pro 或者 Imac ，想要几个27寸的显示器都可以

所有的一切，我们只想要让你干活干得更爽！如果你有更好的意见，也可以提出来大家一起改进。

技术要求：Python or Clojure or Js，如果你React或者ClojureScript写的很好也不错。我们希望你的能力越厉害越好。
## 薪资范围：

5K--30K（学徒工不在此范围）

工作时间不定期，因为我们是专注于一个项目做开发，不是接各种单子，整体没那么累。但是时不时需要配合法律人的要求进行调整，偶尔加班赶下东西还是有的，不赶东西的时候，不管你在家还是哪里耍着，按时把要做的事情做了就行。

我们希望你能够具有责任心，有极强的学习能力，喜欢运动，喜欢分享。

还有什么问题就跟我联系来问我吧;) QQ: 158336429 Email: arlicle(AT)gmail.com

**Comment by zzdjk6** [comment]
看起来不错呢～

**Comment by sanlee42** [comment]
牛逼!

**Comment by ynzkai** [comment]
赞~

**Comment by bigzhu** [comment]
大家都开始狂招人了，给力

**Comment by arlicle** [comment]
谢谢大家啊，帮忙推荐推荐人，机会很好，希望可以保持一个小而精的团队:)

**Comment by danielliao11** [comment]
给力 加油～
