### ISSUE TITLE
一批互联网岗位 by 房星

### ISSUE THREAD

**Issue by samyn** [yncoder/yncoder.github.io#21]
云南房星科技有限公司

主营业务：计算机软硬件的开发、应用、技术咨询、技术转让及技术服务；计算机系统集成及综合布线；网页设计；国内各类广告的设计、制作、代理、发布；企业形象设计及营销策划；计算机图文设计；计算机软硬件的销售；房地产经纪业务

以上blabla，来点干货

我们的愿景：再造房地产经纪生态（我们是卖房子的）
我们的使命：用科技打造高效、信任的二手房交易平台，帮助经纪人获得尊严和成就

不信？

不需要你信，你等着看就好了，无论是笑话还是奇迹，总之都有的看。
# 招聘职位：PHP高级工程师

offer：
10-20k/m，13m/y，5险一金，双休，加班按小时支付法定加班工资，有机会拿房星期权

要求：
经验丰富：三年以上PHP码工
武器精良：熟悉主流框架（不止TP）
团队精神：有良好的协作、沟通能力
训练有素：代码质量稳定，设计优化强迫症深度患者
# 招聘职位：高级产品经理

offer：
10-20k/m，13m/y，5险一金，双休，加班按小时支付法定加班工资，有机会拿房星期权

要求：
造物癖，但不是模仿癖
情商高，但不是政治家
三观正，但不是道德逼
审美佳，但不是艺术家
（高阶岗位，基础技能要求恕不说明）
# 招聘职位：产品经理

offer：
6-10k/m，13m/y，5险一金，双休，加班按小时支付法定加班工资，有机会拿房星期权

要求：
两年以上互联网公司产品经理工作经验
精通Axure使用（入职后本司提供正版授权）

有意者：sendmail:zhangxi@fangstar.net

**Comment by zzdjk6** [comment]
顶～ 感觉这种薪水正常的职位在昆明很少见呀～

**Comment by samyn** [comment]
俺们已经提供了将近一百个这样正常薪水的岗位啦

**Comment by xiao-hongliang** [comment]
昆明本地很有节操的互联网公司阿，赞一个
