### ISSUE TITLE
高级产品经理 by 房星

### ISSUE THREAD

**Issue by samyn** [yncoder/yncoder.github.io#23]
offer：
10-20k/m，13m/y，5险一金，双休，加班按小时支付法定加班工资，有机会拿房星期权

要求：
造物癖，但不是模仿癖
情商高，但不是政治家
三观正，但不是道德逼
审美佳，但不是艺术家

有意者：sendmail:zhangxi@fangstar.net

**Comment by mytharcher** [comment]
同一公司同一时期重复发布，建议合并到 #21。
