### ISSUE TITLE
关于房星的一些话题

### ISSUE THREAD

**Issue by samyn** [yncoder/yncoder.github.io#24]
## “拿钱砸人”的房星

今年以来，随着加入房星的工程师越来越多，房星作为一个初创一年的企业，居然在本地也有了一点名气，但我时有耳闻，在本地的互联网圈子里流传着一个说法，大意是：“房星嘛，就是一帮职业经理人拿着投资人的钱在烧，拿钱砸人玩儿，没几个人在干正事呢。”今天刚好在“昆明开花者”群中，又听到了类似的评论“只看见拿钱砸人的豪气”，作为房星的投资人、联合创始人，我觉得有必要就一些问题做些说明。
## 为什么会觉得我们在“拿钱砸人”呢？

这个问题我思考了很久，我目前想到的答案是，在我们成立之初，就确定了我们要比本地的平均水平高 30%，接近北上广普通互联网公司的水平的薪酬标准。相比本地的许多初创企业，这样的薪酬水平就要高出 60% 甚至更多，也许这就是“拿钱砸人”的出处吧。
## 为什么要这么定房星的薪酬水平？

原因有 2：
1. 本地互联网行业发展水平较低，靠谱的人才难觅，除了良好的工作氛围和企业文化，有竞争力的薪资才是最有诚意的邀请
2. 房星对于我和我的合伙人来说，是一件必须全力以赴的事业，我们希望吸引到最优秀的人才，自然需要为这样的需求买单
## 这一年房星做了什么?

我们完成了两件事：

第一件事，从 0 开始，为线下的一百多家门店，3000 多经纪人打造了一个全平台（桌面、微信企业号、APP）的综合作业系统，业务峰值每秒并发数接近 2000 连接，构建了具有水平自动扩展能力的服务体系，核心业务数据表规模在百万行级，单套环境服务器节点达到 20 个。

第二件事，我们构建了同样全平台的用户端产品房星网，并完成了一个房源展示类网站该有的所有基础功能，并将房星网和房星地产经纪作业系统完成了数据实时对接。

以上这些工作，都是过去一年中，从我一个程序员开始，组建了今天 70 多位工程师的技术团队，从 0 开始逐步完成的工作。我们平均一周会迭代 4-10 个发布版本，一个月会有 2-3 个大型版本迭代。
## 房星正在做什么？
1. 一个能支持多个经纪公司协同作业的平台级产品
2. 一个能支持多种发布媒体、渠道的房源综合展示平台
3. 全面的 3D 户型房源平台
4. 3000 座席的呼叫中心
5. 地产行业的互联网数据动态监控系统
6. 领先于行业的多项业务创新产品
## 关于招聘，房星还要怎么干？

目前的团队规模已经不小，但是房星要完成的目标需要更多优秀人才加入，所以我们还将继续按我们既定的方式扩大招聘规模。从另一个方面来讲，更多的优秀人才，将通过房星的事业，得到真实磨练的机会，无论房星的事业今后如何，这些人，一定都成为改变未来 10 年云南互联网的主力军。
## 关于我

我叫张锡，房星伙伴都叫我 Sam。

我从高一那年开始学习编程，先后接触过 QBasic、Turbo Pascal、Foxpro、GCC、Delphi、.NET、PHP。目前，我已经不是一位还能不断跟进最新编程语言和框架的工程师了，但经过这些年无数行代码的历练，让我能以工程师的思维模式和知识结构去思考技术方向并进行决策。更重要的是，我能去判断我身边的工程师解决技术问题的真实能力和水平。

我也是房星的投资人（非技术入股），每天工作大约 14 小时，每年工作 330 天以上，希望这样的努力能够得到更多成功的可能。我和我的伙伴们是真正的互联网创业者，不是职业经理人。

**Comment by ghost** [comment]
既然官方允许吐槽，那我就不客气了～

说房星“用钱砸人”，那分歧点肯定不在于钱啊!

我第一次正式的认识房星是在15年底的群聚会。来了一位“产品经理”。

他自我介绍的时候说（大意，不记得原话了）：Sam有事来不了，但是不想浪费钱，所以就由他代替。

插一句，我们社区活动的报名费只要人没到是可以无条件退款的。

讲师在分享的时候他几乎都在睡觉。

结尾 freetalk 开始的时候强行安利聊了一波房星（收入高！扎根房地产行业有希望！）但是，我们问他的问题几乎没能回答（核心竞争力是那3000个销售？如何与一线城市的房地产互联网公司竞争？诸如此类…）

他的话题结束之后…他！就！走！了！

房星给一线水平的薪酬对昆明的开发者来说是好事，但是请对我们多一些尊重，不要只在那纠结“钱钱钱”。

-- 希望一天工作8小时以内，有点空就打ps4写娱乐代码的程序员留

**Comment by bigzhu** [comment]
最初耳闻房星，就是老早之前有人说这家工资好高好高。
随之也发生的浓厚的兴趣，但是如楼上所说，几次接触下来感觉并不太好。
有人说这家公司一直在烧钱，没做出什么东西来。因此聚会时候我也特意反复问了，希望能有人反驳这一点，遗憾的是来的似乎并不是技术相关人员，疑问仍然没得到解答。至于我想了解更多关于业务方向，盈利点，技术路线，团队氛围，企业文化，管理和工作方式等等自然也没能知道。
唯一留下的映像仍然是我们资金雄厚，有钱！工资高！
能用高薪来搅动云南这近乎死水的IT环境，我觉得是好事。
ps: 我也想发那么高薪水，无奈囊中羞涩……
只是提个建议：在夯实了薪水的基础上，往上延展一些其他东西可能对优秀的程序员更有吸引力。毕竟很多优质程序员追求的不仅仅是金钱和物质了。

**Comment by samyn** [comment]
## 关于房星的一些补充说明

今天有幸参加了昆明程序员社群的交流活动，认识了很多优秀的朋友，我也就房星相关的一些话题和大家进行了交流，这里整理成文字，便于未到场的朋友了解房星。

## 关于2015年线下聚会的抱歉

那天的活动是我主动申请参加的，从北京回来创业后一直没有和本地社群建立联系，希望利用这次机会能让更多人了解房星。但的确因为临时有事耽误了，为了不想失去那次机会，所以才找了你们说的“产品经理”来临时替我参加。

这位产品经理叫刘宇，是我的合作伙伴，他是一个很Nice的老程序员，只是因为当天分享的主题偏技术，而他已经很多年没有直接从事开发岗位，所以技术话题能参与度的程度不高，是我们对活动的主题的把握和参与态度出了问题，所以没有给当天参加的各位留下好的观感，对此我深表抱歉。

## 关于尊重程序员和技术

说到尊重程序员，房星为了成为一个尊重程序员的雇主是下了功夫的：
- 在房星，上班是不需要打卡的，但是下班加班哪怕只一个小时，我们也会支付国家规定的的加班工资。
- 我们有一个随时能为房星程序员提供热饮的Hacker Cafe和管饱管够的免费零食。
- 房星提供了向所有伙伴开放的按摩椅、健身房和游戏设备。
- 房星为工程师准备的椅子都是符合人体工学标准电竞专用椅，还为有需要的程序员提供用于站立办公的可升降工作台。
- 为了减少眼睛的疲劳，我们为工程师提供的显示器都是DELL高端显示器，工程师可以根据需要申请多个显示器。
-  在昆明这样的四季如春的城市，也会有冻死宝宝的日子，所以我们在工作区提供了空调，尽量减少寒冬和夏日对程序员的困扰。
-  为了让程序员减少一些通勤的时间成本，我们对于居住在公司附近的伙伴给予双倍的通勤补贴。
-  我们尽力保证工作需要的工具的正版化（已经正版化的部分清单：Axure, Navicat, Ext.js, SecureCRT, Office）
-  房星承诺在现阶段至少将15%的源代码贡献给开源社区，这件事情正在进行

以上这些，其实和钱的关系不大，执行成本是大部分企业都能正常承担的。我们之所以做，是因为我们懂得技术的价值、工程师的需要和互联网的基因。

## 房星到底在做什么？

中介卖房子这件事，说起来真是一件让人不胜其扰的事情。我曾经也有一天被打许多电话问要不要买房的经历。所以在开始做房星前，我对这个行业的观感并不好。

最初决定要做，是因为合作伙伴的坚持和信任。慢慢开始接触这个行业之后，内心的坚持又多了一些不一样的东西。

首先，无论你怎么讨厌中介，但是当你需要买房的时候，往往还是需要他们来帮你完成交易。这里面的原因，是对大多数人来说，买房这件事是一件低频且成本极高的决策，客观上需要专业的服务辅助决策。

其次，因为低频且决策成本高，所以获取一个客户，并最终完成交易，一个经纪人需要付出极大的努力，为了成交一个客户，平均情况下，一个经纪人需要拨打5000个电话，为了带看客户，新买的皮鞋不到一个月就踩坏。这一行挣到钱的，大多数是那些能吃苦的农村长大的孩子。这一年听了他们当中很多人分享的故事，明白了他们中的大多数，是通过勤奋劳动来收获的财富。

但问题来了，这个行业的很多让人不舒服的东西，和它可以为年轻人提供改变命运的可能性，为什么就成了纠缠不清的东西呢？

我发现，这个行业的乱象，源于对信息不对称的依赖，甚至在已经被互联网深度整合之后依然如此。现在去主流的房产网站看到的信息，大多数都是由经纪人发布的钓鱼信息。劣币驱逐良币的规律非常明显，如果一个经纪人挂出了一套真实价格的房源，在众多虚假价格的同类房源里，他基本上无法得到来电的。

这似乎成了一个无法解开的结。

竞争激烈-》虚假房源和不正当的手段-》更激烈的竞争-》更糟糕的生态

房星的愿景就是为了破掉这个死结，再造房地产经纪生态。

我们用了半年的时间，完成了一套覆盖全城的地产经纪作业系统，在这个系统底层，完成了对每套房屋进行唯一标识的楼盘字典，以此作为确保系统中房源的准确性的保障。我们开发了以移动互联网为目标场景的经纪人作业系统。并将这些基础设施和连接消费者的产品完成对接。这些工作，都是我们未来要完成的整个蓝图的基础部分。

## 未来房星要做什么？

今天交流过程中，有朋友问道，既然这个行业的区域壁垒如此坚固，那么房星未来如何开拓异地市场。房产交易这个市场里，在交易规模和延伸性方面都是普通商品无法比拟的，如果未来房星能在云南这个区域市场中占据超过1/3的市场份额，这已经是一件非常了不起的成就了。当然，我们也会在这个过程不断的探索能够拓展我们发展空间的路径，这里面包括了进一步拓展房屋销售的后市场，也会包括了房产交易的开放平台方面的尝试。这些领域，都有足以为让房星在未来若干年的不断发展的空间。

## 房星的技术管理体系是怎样的？

房星现在研发中心有70人，分成了9个团队，分别独立面对不同应用场景和产品线的需求，团队之间通过每日协调会、协作工具（禅道）、维基（DokuWiki）和产品发布流程进行协作。团队由项目经理和产品经理协调目标和进度。面向C端的产品，目标和进度由产品经理负责，面向B端的产品，目标和进度由产品经理与业务团队负责人协调负责。
在团队之上，只有两个非专职的机构，分别是技术公会和安全委员会，负责决定涉及技术架构和系统安全的事宜。
我在团队中的角色主要是需求的推动者和“找麻烦”的人，除了产品战略和人事之外，其他的日常事务大多数是由团队内部自组织的方式完成的。

## 房星的技术团队的话语权

房星从一开始就将自己定位为互联网公司而不是一家地产公司或者是服务公司，所以房星的投资人和团队都希望技术能在房星未来的道路上发挥重要的作用，这是我们的愿景，也是我们一直在努力的方向。

## 其他

非常欢迎社群里的所有创业者、工程师，有机会来房星交流，从开始做房星的第一天开始，我就有一个想法，在这个互联网的荒漠城市，我希望和整个社群一起抱团取暖，一起建设云南的互联网生态，我们在努力，也希望能得到社群的理解和包容。

## 我和房星的联系方式
- 微信：ynzhangxi 
- 微博：云南张锡
- 电话：13577062070
- mail：zhangxi@fangstar.net 
- 房星地址：日新中路广福城A11-3栋-11楼（前福路和日新中路路口西南角）

**Comment by LeeBin1984** [comment]
fangstar 是一家绝对靠谱的雇主。改变一个行业一个生态，完成信息正在对称。房星人正在努力。

**Comment by arlicle** [comment]
我觉得你们做的事情，努力的方向，运营的模式，与互联网是很违背的，有那么好的资金条件更是应该花10倍100倍的薪水去找顶级的技术人员，而不是找一堆普通人。我说话比较直接，我觉得你们很危险;)

**Comment by zzdjk6** [comment]
我听下来感觉是这样的：
1. Sam人很nice, 自己分享和回答问题的角度与逻辑都很清晰
2. Sam对自己团队和产品的定位及发展方向都很明确

个人觉得，在一线城市待过就不会惊讶它的薪资水平；在大的互联网公司待过也不会惊讶于它的技术团队规模。只是这两点同时发生在一个互联网行业不发达地区的互联网创业公司，就会比较令人瞩目吧～

至于人力资源需求，我猜更多是和行业背景和业务需求有关。
律品由一些顶尖的律师和几个顶尖的程序来做，走“小而美”路线，棒棒哒～
房星可能就是需要那么多工程师来推进它的各项业务，我觉得也很正常～

不同背景的人分享和碰撞着不同的观点，应该算是交流活动中极有意思的部分吧 :)

**Comment by samyn** [comment]
谢谢 arlicle 对于”危险“的提醒，从创业第一天开始，我们无时无刻不在提醒自己，巨人就在我们的门口，随时会进来吃掉我们，但是生命的意义不就在危险下面探寻可能性吗？

没错，我和我的伙伴都是普通的人。但在我眼里，他们可不是“普通的技术人员“，他们是在这个城市里最棒的工程师，我们会不断寻找和他们一样优秀的新伙伴，但我们更倾向于不断的提高他们的薪资水平来配合他们对房星的贡献和自身的成长，也希望将来能给他们10倍，100倍的回报。

至于”做的事情，努力的方向，运营的模式，与互联网是很违背的“这句话恕我愚钝，实在无法理解，希望能明示。

**Comment by arlicle** [comment]
就是看起来表面上各种很很互联网化，但是实质核心的东西没有这样。你需要认识到诺基亚再强大是造不出Iphone来的;) 也或许我了解的还不够多，以后有机会再深入交流;)

**Comment by bigzhu** [comment]
其实我昨天也特意问了。
强业务相关的，深入且为业务服务的系统，这样的模式是很常见的，因为本来就不是互联网。我刚毕业进的就是这样的上千人的公司，一个项目动用上百人。
sam的回答也是他们确实是在夯实业务系统，还并没有往互联网发力。

不过人多了，问题就复杂，人与人之间的各种利益纠葛，会导致很多管理问题，管理成本会很高。
另外，我以前的公司现在也是在努力学习用小简快的方式来做业务，毕竟并没有人规定一定要用这种大而密集的方式做行业业务系统。
