### ISSUE TITLE
2016 上半年社区活动

### ISSUE THREAD

**Issue by gc87** [yncoder/yncoder.github.io#25]
形式：主题分享 + 技术讨论
嘉宾：SaintDan，笑笑就好，琳琳的小狗
主持：Durandal
时间：6月11日 下午13:00
地点：盘龙区新兴路 霖岚国际广场a座9楼 咖盟咖啡 [地图导航](http://j.map.baidu.com/djF9B)

主题分享：
- Docker使用指南 _by SaintDan_
- 怎样和律师一起写代码 _by 笑笑就好_
- 代码十年 _by 琳琳的小狗_

技术讨论：freetalk

说明：社区的一系列活动，旨在通过互联网技术话题的交流分享，活跃昆明本地的技术交流气氛，促进社区成员之间的交流合作，共同改善我们的技术、创业环境

活动须知：参加本次活动无需支付场地费用，无需报名，活动现场请凭个人意愿购买饮品，个人产生的停车费、车船费请自行处理

**Comment by soooooot** [comment]
赞赞!!报名报名

**Comment by 88250** [comment]
刚好是端午放假，要回老家参加不了 :joy: 

![image](https://cloud.githubusercontent.com/assets/873584/15733097/39c3462e-28b5-11e6-911c-565a7bf62e73.png)

**Comment by xiao-hongliang** [comment]
支持支持，必需得参加啊！

**Comment by codeterminater** [comment]
如何报名。

**Comment by gc87** [comment]
@codeterminater 直接来就行了

**Comment by gc87** [comment]
@88250 遗憾了

**Comment by mytharcher** [comment]
报名！

**Comment by 88250** [comment]
@gc87 争取那天早上回昆明，下午赶过去参加，看情况吧 :smile:

**Comment by kentzhang-geek** [comment]
正常情况下就来

**Comment by mytharcher** [comment]
话说你们都带着各种牛逼的键盘来啊！

**Comment by YuYanDev** [comment]
窝应该可以来～

**Comment by yanxiangrui** [comment]
支持

**Comment by zzdjk6** [comment]
支持～ 报名～

**Comment by oldrev** [comment]
可惜来不了

**Comment by ghost** [comment]
## 主持人的活动总结

#### 『Docker使用指南』

![img_0947](https://cloud.githubusercontent.com/assets/4213847/16034200/0043c1f2-3243-11e6-93af-57687d7085c7.jpg)

`Docker` 虽然已经不是新鲜东西，但是在云南的团队中推广并使用`Docker`的团队却屈指可数，究其原因大概是因为本地团队对『项目运维』方面并不重视与`Docker`上手难度导致的。

SaintDan为了安利`Docker`完全豁出去了，直接在生产环境中演示怎样用`Docker`解决部署中遇到的实际问题，现场观众也对`Docker`表现出了浓厚的兴趣，相比以前纯技术分享的结果，这一次可以说是『工程化的胜利』:)

#### 『怎样和律师一起写代码』

![img_0962](https://cloud.githubusercontent.com/assets/4213847/16034000/ee6d0912-3241-11e6-92ab-92a05afc86b6.jpg)

互联网、Clojure、远程工作。

『律品网』是带着这些 Cool 到极点的关键字，突然出现在社区的。

笑笑就好一边述说自己过去10年的创业经历与律品网诞生始末，一边讲解自己对于创业与团队的理解，为社区带来了属于一线互联网创业团队的经验。

顺便还留下了名言：

> 招不到合适的人，我多加加班就好啦。

还请多注意身体啊！

#### Freetalk：创业

接着律品的创业话题，我们圆桌讨论的主题也是与『创业』相关，两位完全不同性质团队的 Leader 为我们介绍了他们的团队、产品与对未来的展望：

张天羽的团队几乎是一个纯技术团队，他为我们讲述了创业遇到的问题，比如欠缺商业方面的资源，没有找到合适的商业模式等等，也介绍了一些他们在上述问题上的解决方案；

Sam 的团队 -- 与张天羽的完全不同 -- 是建立在成熟商业模式与商业团队之上的技术团队，人数接近 100 人，工作内容与概念中的“互联网”也有一些差别；

结合律品的分享，为我们带来了许多对于『互联网创业』的讨论。

## 最后

![img_0969](https://cloud.githubusercontent.com/assets/4213847/16034003/ef80980a-3241-11e6-9f50-723b3a116b53.jpg)

感谢各位参加活动的社区伙伴，

期待下次活动（顺便把玩一下高级键盘 A_A）

**Comment by scriptfans** [comment]
很遗憾，这些天闺女生病住院，一直耗在医院没有能参加，只能期待下次咯……

**Comment by MuseTools** [comment]
期待下次活动

**Comment by Beaze** [comment]
远程精神同在
