### ISSUE TITLE
社区访谈：自由职业者与远程工作那些事

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#27]
## 活动信息
- **时间**：2015年2月7日（周六）下午2点
- **地点**：北辰财富中心CD商务公寓16楼，[查看地图](http://j.map.baidu.com/n4cwm)
### 访谈嘉宾
- 严俊羿：前端工程师，2013年以Freelancer身份全国旅行，14年初回到昆明开始正式的自由职业生涯，同时在做Remote工作。
- 王楚安：6年资深Freelancer，曾经拥有自由职业的团队，最近脱离自由职业身份，开始上班。

> 感谢[恒翌科技](http://highwe.com/)提供宽敞明亮的会议室给我们进行这一次采访。也感谢嘉宾与现场听众的捧场，让这一次采访整个过程都非常开心。
> 
> 由于设备与个人能力限制，这一次采访并不会提供原版录音，有兴趣的朋友可以直接来现场旁听，还有机会与嘉宾互动。
> 
> 感谢**Yanjunyi**, **William**, **风雪**, **So9t!**, **Bigzhu**等人支持第一次访谈活动。
> 
> 我是重度拖延症患者，请见谅。
> 
> --采访者：张锐
### 成为自由职业者

**D**: 那么，**Yan**能不能先介绍一下，是为什么成为自由职业者的？

**Y**: 主要是因为家里的原因要回昆明。既然回来就需要一些谋生的手段。但是昆明IT行业并不发达，很难找到和原来一样高水平的团队。后来就想，刚好自己主要是做需求量比较大的web这一块，所以就选择了自由职业。当时的想法是边玩边做，所以就开始在国内玩，后来发现这个想法不太现实，干脆就纯玩去了（笑）……真正回到昆明是13年底，大概10月份才回到昆明，一直到14年上半年，都是自由职业者。因为自己很早以前就向往自由职业的状态，所以就试了一下，感觉还可以，时间上很自由。白天处理杂事（政府部门就只有白天可以去弄……）晚上再来工作，这样的感觉。

**D**: 做起来，压力会不会比上班的时候更大？

**Y**: 其实很大！非常大！经济压力非常的大！因为一个人去接单子这个事，单子少的时候，一旦断了，那么经济来源就断了。单子多的时候又没法一个人做好几个单，总之只有一个人的精力。W也可以聊一下他这方面的(经历)

**W**: 我原来也是经常会遇到这样的情况，有半个月什么事情都没有，过了一段时间，突然就很多项目涌过来。像是年底的时候各个单位都会组织一些活动，会有一些工作是跟活动相关的，这种类型。

**D**: 那么 **William** 为什么一毕业就开始做自由职业的工作？

**W**: 其实最早，并不是冲着自由职业这个方向去的，是想要去创业来着。其实我在编程这个方面主要是自学的。最开始是找别人做，但是人走了以后，事情还没做完，必须得马上把工作接上，所以就靠自学着把这个事情就做上了。（**Y**: 自学成才啦，哈哈哈。）然后就一直这样做下来，后面开始有点享受这样自由的状态，就开始觉得是自由职业了。

**D**: 但是我理解创业的时候工作压力蛮大的吧？为什么时间还能变得更自由了？

**W**: 这个自由是相对的吧。我可以自己安排什么时候去工作，晚上工作的话，白天就空出来了。上班的话就不能像这样安排自己的时间。（**Y**: 这应该就是当老板的状态吧（笑））

**D**: 后来创业的那个项目怎么样了呢？

**W**: 那个项目，最开始我们做的并不全是计算机这个方向，是BPO - 商业流程外包。后来在做的过程中，我们发现，这种工作，一般来说是比较大的企业在做（**D**: 是类似咨询公司那样的吗？）对的。我们在做的过程中碰了很多壁，但是也接触到一些小的客户，有一些软件外包的需求，所以就接过来做。后来陆陆续续就转到这一块了。

**D**: 就这样整整6年都是和别人合作做软件外包的工作吗？

**W**: 并不是那样，我做的客户其实很杂。我没有统计过，不过要我估一个的话，大概已经100-200家公司了。但是每个项目都很小，因为作为自由职业者，没法像公司那样去接很大的项目。特别是在前期，真的是来了什么项目就做什么项目了，很小的东西都做。其实到现在，我再去回想当时，我觉得有两个东西没有做好。就是，其实当时已经积累了一些长期的客户，有的客户是很好的，项目很稳定，费用也比较高；另一些的项目就相对杂乱一些。我当时没有做好项目与客户的选择。有一些时间相对来说就浪费了。另一个就是团队没有组织好。
### 自由职业者的生活

**D**: 那你做了这么多公司，有没有哪种类型是特别特别坑的？

**W**: 回款方面特别坑的倒是没有。项目方面……有一个国内的客户是比较坑的。因为我做的主要是欧美那边的客户，有一个美籍华人回国创业的时候找到我，他的公司是做一个像聚美那样的，卖打折奢侈品的网站。在那段时间，不像现在有很多家，他那个网站叫做<屏蔽>网。那个项目做得特别痛苦，第一版做了5-6个月的时间，结果第一版突然全部推翻了，重做。

**D**: 那给钱了吗？

**W**: 钱倒是给了。但是做得太痛苦了。一方面是需求变更太大，另一方面可能是我们在那个阶段做出来的质量上也不太好。好在后面这个项目，从技术这个角度来看没有什么问题了，但是这个项目后来因为一些其他方面的原因，还是关掉了。

**D**: **Yan**你有没有遇到过特别坑的，给你印象很深的客户？

**Y**: 这将近一年接了一些零零散散的小单子。遇到的坑还是挺多的。我感觉越小的单子坑越多。

太大的单子我这边比较难接到，接到一个人也不一定做得下来，所以一般是小单子。包括一些亲戚朋友的单子，这种有感情分在上面的，也很难去追他的款。后来还有一些朋友介绍的单子，做下来客户那边不想继续下去了，这事一拖就没消息了。

去年10月份结果一个单子，是一个在美国的台湾人，他好像也是做算法那块的，想把自己的个人网站外包出去。当时我在 [Elance](https://www.elance.com) (注: 一个自由职业的中介网站，下文中提到的 oDesk 也是一样)上看到他的邀请邮件，然后就上去看。我去看的时候这个单子被别人接了，我当时是抱着试试的心态给他发了邮件，说你需要的这个技术，刚好是我非常擅长的 -- 他是想要用 Jekyll 在 Github 上建个站 -- 这一块我特别熟。他就回邮件说，那可以呗，要是之前外包的人没有做成，那就交给我来做。

过了一段时间他真来找我了，说之前那个人没做成，然后我给他报了价，用了2-3个星期左右给他完成了。结果到10月份以后，就再也没有他的消息了。所以这个项目……(**D**: 恐怕是跑单了) 嗯，因为我是和他在线下做这个项目的，如果是在 Elance 平台上做，因为有保证金，所以这方面的风险会小一些。现在国外最好的平台我觉得应该就是 Elance 了，加上他把 oDesk 收购了，所以我觉得在那个上面做的画，可能会稍微靠谱一点。

**D**: 那 **William** 有没有遇到朋友、亲戚介绍过来的项目，做到后面不太好意思去要钱这样的情况？

**W**: 这个我还没有遇到过，但是像刚才 **Yan** 讲的这样的情况，我做了一段时间之后也遇到过这样的。一个客户一开始合作得很好，忽然有一个项目上我没有让他提前给我打钱，做完他就消失了。后来我就总结出来，完全不能给他机会……（**Y**: 还是要按照流程办事）是的，如果你给他机会，让他可以赖账，那么他就一定会赖了。

**D**:会不会在回款的时候遇到客户也不是说不给，但就是不怎么搭理你了的情况？

**Yan**:有两个是亲戚的项目，他们做到后来，关注点就不在这个项目了。这个就没有办法，因为他们自己都不管这事了，所以就无限期拖延了。所以，我觉得在这个过程里就要筛选你的客户，搞清楚他是什么样的一个人，他会不会按规则去办这个事。如果他是又不太懂，又想法比较多的类型，就不太好弄。（**D**: 这就是传说中的“就差程序员系列”了，是吗？（笑））因为很多行业对信息化都有很大的需求，但是他又不太懂，所以很多情况下他就会低估你的工作价值。

**D**:在挑选客户和项目的时候，能不能总结出什么样的经验？

**W**: 我在做自由职业的过程中发现，一般来说客户都不会很专业。因为专业的客户一般是不会选择自由职业者的。但是我们在做的过程中就需要把客户往专业的方面引导，做到后面就能感觉到，和这部分客户的合作是非常顺畅的。

**Y**: 有一次，我有个亲戚介绍我去做一个政府的项目，接单是一个专门做软件销售的公司，他可能对软件了解一点，但是了解的又不是特别深，他在给说需求的时候就是一些大而泛泛的话，比如:我们要一个门户，一个平台，数据接入到什么什么的，他在说这种话的时候就要提高警惕了。这时候如果没有专业的人员帮他拆解这些需求，帮他形成一个产品化的描述，我们作为开发人员，就很难去完成他的要求。因为他可能根本没有想明白，只知道我要这样的东西，但是这东西要长什么样他自己都不太清楚。

**D**: 那我总结一下我们刚才聊到的就是两个关键字。第一个就是“亲戚”，因为他们不太了解软件开发这件事，所以需要对他们提高警惕。另一个就是“政府项目”。

**Yan**:对于个人来说，政府项目是很难完成的。首先是如果按照正规流程，个人是不具备项目竞标资质的。即便是别的公司拿下项目来分给个人做，这也是很不靠谱的一件事，因为个人和公司之间没有任何的约定，个人只是一个劳务，究竟公司会不会结钱很不好说。特别是，政府项目结款的周期特别长，对于个人来说是拖不起这么长的时间的，中间这个过程，个人拿不到钱，吃饭都成问题，而且这个过程中还要改这改那无法避免的。

> (现场听众乱入，谈政府项目)
> 
> **风雪**:政府项目不止是投标和开发，后期维护要求也很多，很容易坑进去。
> 
> **Bigzhu**:我有一个朋友开了公司给政府做项目，但是一直被拖着不节款，后来他把房子卖了，车子也卖了，终究还是没能撑下去。

**D**: 做自由职业项目的时候会和客户签合同吗？

**W**: 主要是我的客户大部分都是国外的，签纸质的合同非常麻烦。所以一般都是谈好了以后，我们到一个平台上，在平台上操作，一般就不会有问题。

**Y**: 是的，在平台上有一些类似支付宝一样的担保功能，他(客户)需要先把钱打到这个平台。一旦开始项目，这个钱就锁定了。可以规避回款方面的大部分风险。虽然平台会扣掉一定的费用，但是安全就有了保障。

**W**: 而且在平台上还有个好处，是类似淘宝一样可以积累信用。慢慢做着信用就积累起来了。

**D**: 在做自由职业的时候，如何把注意力保持在工作上的？

**W**: 做自由职业对自律性的要求是比较强的。而且我当时是租了一个地方做工作室，像上班一样，每天早上过去办公。

**Y**: 我主要是在家里，虽然在家里一般不会有什么干扰，但是家里的人偶尔回来打扰我。后来我实在不行了，就必须把自己关在房间里，把自己和家人隔绝起来，这样情况会好一些。但是大多数情况，还是看客户的要求，如果他要求是某个时间点，这个时间点就会敦促我工作。

**D**: 也就是“deadline是第一生产力”啦！（笑）

**Y**: 对，毕竟这个deadline也是自己评估出来的。

**D**: 那有没有一些手段或者技巧来帮助像我这样自律能力不是特别强的人注意力集中到工作上？

**Y**: 首先给你的hosts里填几条 v2ex啊，zhihu啊，把im都关掉，尽量通过邮件和电话联系。在公司我们也要求像这样，如果有急事就直接去找当事人，不要在im里聊工作的事。

**W**: 确实是，我工作的有几年几乎没有上过QQ了。这两年上班了反而QQ一直在线了。（笑）

**D**: 做自由职业有什么样的要求？需要具备什么样的技能？

**W**: 专门去学习某个方面技能，我觉得其实没有必要，你在做的时候你的技能面就会越做越广。因为做自由职业的时候，客户的很多其他东西都需要依赖你，所以你都需要去学习这方面的技能满足客户的要求。

**D**:那么非技术的方面有什么需要准备的吗？比如说需要有多少存款才能开始自由职业的生涯？或者要单身？

**Y**:单身这一点，我觉得还是看家庭成员的观念。如果父母或者老婆比较支持，比较开明的话其实也没什么关系。如果是家里不理解的话这事就很难办。

**W**:我觉得还需要个人有责任心。一个是客户把项目交给你，你能不能在没有任何帮助的情况下把这个项目完成。另一个是除了把项目做完，会不会有责任心帮他考虑，做到比他的要求更好。

**Y**:像是健壮性，拓展性，还有一些稳定、安全方面的一些东西，客户其实是没什么概念的，所以这些都应该为他想到。

**D**:有没有和别的自由职业者合作过？

**Y**:有合作过。但是还没有成功过（笑）。因为我接到的都不是特别大的项目，合作的需求不是特别的强烈。

**W**:我的合作主要是之前公司的内部。

**D**: 对于自由职业者来说，PHP是不是最好的语言

**Y**: 其实主要还是看你对哪种技术更熟。因为做自由职业其实是在最短的时间里，用最少的劳力完成一个项目。我选择PHP一般是因为客户的项目需要部署，客户有的时候会自己买一些VPS或者云服务。一般都是支持PHP的，部署PHP也很快。另一方面，PHP也有很多成熟的产品，像WordPress 这样的，在国外的开发者当中非常流行。(**W**:我原来接的项目中大概有50%都是用WordPress来做的)在国内也有这样的情况，比如客户说:我要一个论坛。那一般就是 discuz!，像商城一类的项目，一般就是ecshop。就算不是完整的产品，有时候也会指定像 ThinkPHP 这样的框架。这算是PHP这个语言比较大的优势。
### 结束自由职业

**D**: 为什么结束自由职业或者会因为什么原因结束？

**W**: 主要有两个原因。一个是自由职业做得太久，每个项目做完了就交付了，很难完成一些个人的积累，比如技术方面的；另一个方面，虽然很自由，但是经济上会有很大压力，收入很不稳定。

**Y**: 因为个人精力有限，没法做所有的事情，总会有接不下去的时候。我去年上半年，北京那边找到一个兼职的工作，有了一份兼职的稳定收入之后，还能相对的自由，压力小了很多，工作就很舒服了。我想在做自由职业的时候，因为可以接触很多客户，希望可以把客户的需求做一个总结，总结出一些规律，或者一些共有的需求，找到自己做某个产品的思路或者方向。

(休息了大约15分钟)
### 远程办公(Remoting)中的个人

**D**: 好的现在我们开始下半场，**Yan**你是怎么样找到这个remoting的工作的？

**Y**: 这个可能还是跟我以前在百度工作有关系。出来了以后和同事还有一些联系，然后，大家也都知道我们这边的工程师还不错，如果有事情的话可以找我们，我们基本上都能搞定，然后我也会在我们之前的圈子里边，去告知大家说 —— 我现在是一个自由工作者，有活的话可以找我，大家知道以后就慢慢的传播出去，可能就有他们第二层的圈子知道了以后，就通过以前同事这些关系去介绍，最终找到这些团队。

**D**: 那么你从自由职业回到现在这种全职的 Remoting 的工作，中间有没有经历过什么样的转变？或者说是对自己的一些什么样的调整？

**Y**: 我觉得 Remoting，最大一个转变就是你自己不用去找活了！算比较好的一个事情，因为以前所有的活都得你自己去找，那就需要边跑市场边做技术。尤其在初期，你还没有积累特别多客户的情况下，可能你做这个客户他只是一单子的生意，他后来没有更多的需求了，就不会找你了，当你积累了一段时间，像 **Willam** 一样有稳定的客户了，他又持续的项目给你的话，那基本上也跟做 Remoting 差不多了。

**W**: 但是结算的方法会不一样。因为原来都是按项目去结算，然后我不做了之后，原来我做的有个项目，客户需要我去维护些东西，也是类似的等于聘用我，可能每个星期会有那么两三封邮件，可能会有些小东西去处理，然后他固定的每月算给我钱，这种收入的方式也是固定的。

**D**: **Willam** 从自由职业回到上班这个状态以后，有没有什么觉得不太适应的？比如早上必须要求早起呀之类的？

**W**: 说实话，完全没有不适应的，其实自己原来做这个自由职业的时候，压力蛮大的，有些时候还是觉得自己蛮拼的。后来去了公司之后反而会觉得放松了一些。（笑）

**Y**: 因为有公司这个框架在框着你对吧！

**W**: 其实我原来也处于上下班那种状态，其实那会儿也是24小时待命.(**Y**:只能自己管理自己对吧，到公司以后是别人管你(笑))

**Y**: 我当时去北京第一个团队的时候，我就有一个感觉就是——当时已经自己做了将近半年，又有大半年是在外边玩的，很长时间是没有跟人一块合作的，然后去了公司大家突然一块写代码，好久没有跟大家一起写代码有点感动的感觉。

**D**: 就好像又回到了一个前线的战壕里，旁边很多兄弟跟你一块这样的感觉吗？

**Y**: 一个人久了也会觉得有点问题怎么找不着人问呐，就是这种情况。

**D**: 那你在做remoting的时候是怎么跟同事合作的？

**Y**: 我们大多数是通过邮件的

**D**: 会不会有这种特别急的修改，但是你当时没在线？

**Y**: 很少，一般都会提前知道，这个东西要很快修复的话，收到邮件，一般在一天之内都会去解决掉的。

**W**: 这种情况像我倒是出现过，有时候Gmail那种，访问不了，忽然五六封邮件出现在信箱，一封比一封还急，但是我接国外稍微好一点的好处是，我下午下班刚好是他那边早上九点，伦敦的客户，他也一般在早上发现了给我通知，正好下班在家就处理问题。

**D**: Remoting 的团队或者是客户会不会专门把任务拆分一下？因为他们可能现场有一些工程师嘛，把比较着急的或者需要迅速沟通迅速解决的交给自己的工程师来干，然后把这些相对来说，时间要求不太严格的分发给我们做？

**Y**: 他们会有一些自己的规划。尤其是美国的一些公司，合作了以后会发现，他也是希望去找一些低成本的人力帮他完成一些普遍的一些工作，但是他自己的团队去完成一些需要更集中的一些工作，他的一些更专业更核心的东西。那他在工作上就会有一些考虑，哪些不重要的工作去包给外包的人或者远程的人去做，这样就可以让整个团队合作起来更加流畅，各个层次都不会相互有影响。

**W**:我这边，(如果有特别着急的工作)他们会把我加到他们的facetime。

**Y**:也就是他分配给你们的任务一般是时间要求上相对不太高的工作，在这方面是有权衡的。比如说我们现在这样的话，他把整个产品都包给中国的这个公司来做，把另外的一个手机平台的工作包给印度的公司，多个团队同事在帮他做事情，但是每个团队里面又有一个负责人，去负责把控下面的所有事情，去协调。
### 远程办公中的团队

**D**: 那他们是怎么把控你们交付的质量和交付的内容的，会有专门的人来把控吗？

**Y**: 一般是他们那边的产品经理直接 review 你的工作成果，他们要把你的产品部署到 server 上，然后他会去看，去 check 每个细节，最后去 review 你的成果，如果有问题的话，他会继续给你 ticket，让你去解决。

**D**: 那我想问一下 **william** ，你现在的团队，你觉得你愿不愿意接受 remoting 的人？

**W**: 我觉得这个你倒是提醒我了，还是可以的！（笑）（**D**:完了，我好像做了一件不太好的事。）这个不至于，反正我觉得，这种方式的合作，只要人靠谱，还是可以的。

**Y**: 但是我觉得这个问题是问反了，你是想在昆明去找外地的远程工作者的话，昆明本身的待遇水平不是特别高，你怎么吸引到他们？

**W**: 问题在薪资上。

**Y**: 比如你去吸引大理的工作者。（笑）

**D**: 只能往第三世界国家去靠了，是吧？

**Y**: 我这边实际上是北京的团队在招我在云南的这种工作者对吧，或者美国的公司在招北京的工作者，对他们来说成本比较低，但相对云南的水平来说算比较丰厚了。尤其是以这种劳务合作的方式的话，他甚至不用上税，不用上社保这些情况，一下子少了很多成本。

**Y**: 其实一个人的人力成本是减半的，如果你在北京招一个月薪三万的工程师的话，他的人力成本至少是六万，公司最终付出的成本是六万这个样子

**BigZhu**(以下称 B): 我觉得这个方式可以在云南试一试，因为 remoting 的话他也不属于公司的正式员工。

**Y**: 对，你在这方面可以省下三分之一到四分之一的成本，还有一部分就是你的办公的成本，你要租办公室，办公室就可以少租一些了，如果公司有的话就另说了，但是如果你是需要租办公室的一个团队，你甚至可以不租，因为大家都在各处。

**D**: 那么，作为团队这一边，应该怎么兼容 Remoting 呢？
**W**: 我觉得这种兼容要做到真的不是太难，基本上有一个任务管理的平台就基本上解决了。

**D**: 就是说从管理层面上来解决吗？

**Y**: 你需要建立一些制度，或者是流程，去管理你的所有的人员。比如说，你可能需要每周有个例会的时间，大家汇报一下进度啊或者是工作情况，你可以召开视频会议，语音会议对吧，通过这样的方式建立沟通，因为在 remoting 大多数情况下你是很少需要沟通的，旁边没有人了，你也不需要跟客户沟通。就跟进入公司一个团队一样，刚开始可能大家不是很熟，也会出现很多沟通的问题，但如果经常合作以后，都知道对方的沟通方式。

**D**: 我想问你们一个问题 —— 现在我们公司在招人的时候也遇到很多困难，我就想先跟你们讨论一下 —— 就是说公司在昆明招人，或者招 remoting，那种更划算一些？还有，我现在招聘remoting的同时自己是不是还要有几位工程师，解决一些时间要求特别高的问题与核心问题？

**W**: 完全采用 Remoting 这种方式的公司是有的。

**Y**: 像我们公司其实就是这样的一个公司所有人都是 remoting，因为所有人都不去办公室，没有办公室了就，所有人都不见面的，大家可能临时有事了就见个面。

**W**: 会不会定期去一个地方见一下？

**Y**: 有，比如说去年，我相当于出差嘛，去了一趟北京。大家都聚到一块，可能这个版本比较着急或者比较重要的一个版本大家过来一块开发一下，大家认识一下交流一下，相当于年会这种性质的，还有公司下面还有几个创业产品，他们在孵化，那个团队的人就需要定期去碰个头，或者开会说一下想法啊，有些问题怎么处理啊。需要讨论的时候他们还是需要碰面的。

**D**: 那我就有点奇怪，有一些公司他会花钱去做 team building，但是remoting又是另外一个模式 —— 大家都不见面，偶尔就是工作上面需要见面就碰一下。

**Y**:但是还是需要，公司让大家吃个饭啊，至少要让你的团队成员之间也产生互相的信任，那么他们合作起来才会比较顺畅。在我没有见到他们之前，的确会有一些沟通上的误解，比如说——这人发邮件的语气怎么这样啊，在见到他之前你会觉得跟他说一个问题半天没有说清楚，但是见面的时候会发现这人就是这样的，聊起来人还是蛮不错的，但是发邮件他就是这种样子的，熟悉了以后合作上就会好很多。就是你需要一个职业化的人去做事情，这个是必须，所以（面对面沟通）还是需要的，因为人本身有这种情感需求。

**D**: 那对于我们在昆明的开发者来说，**做 freelancer** 或者 **找一个本地相对来说比较靠谱的公司**或者**remoting**，你们觉得哪一种方式是相对来说是更好的方案？

**W**: 看个人吧。

**Y**: 每一个人他需求不同。

**D**: 对创业者来说呢？

**Y**: 具体看吧，因为我觉得你自己去主导一个创业的话，那你尽量是要找本地的人。因为你在创业的前期会有非常多的事情需要去沟通，除非你建立了一个稳定的基础之后，可以把日常的一些任务分包或者是给远程的其他人去做，但是核心的东西你还得自己去做，所以如果你自己主导创业的话，你还是要去找本地的人，在面对面中沟通。

**W**: 还是要看项目(具体做什么)来决定工作方式，单纯从自己爽不爽来讲就有点太……(不切实际了)

**D**: 那你最希望的是以一种什么样的方式继续自己的职业生涯？

**Y**: 最终的目标当然是天上掉钱啦！（哈哈哈哈哈哈）

**D**: 这个太终极啦！

**Y**: 其实只是一个比喻嘛，就是说你做产品有一直持续不断的稳定收入，又不用你操太多心，我觉得大家每个人都应该会追求这种财务自由吧。

**D**: 就是人身自由和财务自由是吧？

**Y**: 然后完了以后呢，可以去做你想做的事情，比如说去做木工啊（哈哈哈哈哈）

**D**: 你是在木工里边找到乐趣了！

**Y**: 还没有，就是比喻一下而已。或者说去旅行啊，现在还有许多自由职业者，边旅行边工作。跟我同期旅行的一个同事，他从北京出发，骑自行车一直骑到东南亚去了（众人: 噢噢噢~~~），每天晚上他还写代码（**D**: 太有劲儿了！），每天帮他的一个挪威的一个客户做黄色网站（笑），他在 oDesk上找的，后来客户也是稳定了以后就长期有事情找他做，然后他还介绍我去帮他做，但是我玩得太开心了，就不想干活了。

== 警告！未满18周岁请不要阅读以下部分 ==

**W**:这种我也接到过，很短期的一个小项目

**D**:后来都做了？网址都留下来了？（**Y**:求种求种）（哈哈哈哈哈~~~）

**W**:带社交的脱衣舞互联网站

**D**:像那个myfreewebcam？

**W**:它不是给看的黄色网站，是脱衣舞娘？

**D**:九十年代那种聊天视频网站（**Y**:就视频聊天网站嘛），那就像那个myfreewebcam的网站？

**W**:最终是要走线下的约炮的

**Y**:那不是约炮，那是交易

**W**:就是交易

== 回到老少咸宜部分 ==
### 现场问答

**D**: 那今天的采访的部分已经结束了，接下来就是提问的或是聊天的环节了。首先就是 @**风雪** 在我们的页面上提了一个问题: 他想要了解一下，如何从组织内的工作或者说从工作状态切换到freelancer的状态，这样的一个切换需要些什么样的知识的储备，或者是心态上的转变？

**Y**: 心态上的转变，你首先要想明白你能承担多长时间的风险。（**D**:就是看一下自己的银行卡吗？(笑) ）这是一方面，然后就是这么长的时间里面你能不能找到客户。至少是第一个客户，或者是有质量的至少是能拿到钱的客户，你要对这个事情有信心。我当时还算是比较有信心的，觉得这个应该没问题吧，所以就出来做了。

**D**: 先拿到客户的还是先离职的？

**Y**: 先离职的。裸辞！

**Y**: 这是一方面的准备，然后就是你家里面的人支不支持你，毕竟你不去公司上班人家说你整天在家里干嘛呀。刚开始我妈也不能理解我，觉得你在干嘛呢，到底是做什么工作的。（笑）

**D**: 总觉得会比较奇怪，宅一样的感觉！

**Y**: 后来她就习惯了，时间长了也就习惯了，而且你有收入的话，她就不会在意这些。其实是在做正事，不是整天在家玩游戏。

**So9t!**: **Willam** 在和国外的一些客户接触的时候，遇到需求不明确的单子是以什么样的方式沟通的？

**W**: 各种方式都有。其实有些时候我发现有些客户他对项目只有一个概念，然后我对这个概念比较感兴趣，就会去跟他不停的讨论，最终把这个东西落实掉。（如果是比较无趣的，需求又不明确就 PASS 了）。

**B**: 我有个问题想问一下，(Freelancer 与 Remoting的)健康怎么保障？比如与客户（沟通）有时差，会不会影响到你们的休息？

**Y**: 不会，这个是跟客户沟通好了的。团队也知道你时区在china，你是东八区的时钟，他那边的时钟是太平洋时间，他们会去算，这个邮件发出来，你什么时候会去处理。甚至他召集会议的时候也是会给每个团队的时间全部列出来，计算出在你们当地时间什么时候，一般都会照顾到。不过我觉得我们老大是个工作狂，任何时间都在发邮件（笑），我白天的时候发现他怎么发了封邮件，然后到晚上他怎么还在发邮件（哈哈哈），24小时都在干活

**B**: 工作的状态有两种极端，一种是自制力特别差的，还有一种是本身是个工作狂，我们有个同事做remoting，挺担心他的健康状况。

**D**: 对每次见他都觉得他瘦了。

**B**: 每次见他都越来越憔悴。

**Y**: 我觉得健康是你自己要去管理的，比如我之前是每周持续去跑上个两三千米，户外活动，自己调节的这种方式。因为没人管你，而且这种习惯也是要你慢慢培养的，在北京的时候，基本上也经常去运动，有这种意识有这种习惯以后，还是靠自己（管理）。

**B**: 有其他好办法？

**Y**: 因为没人管你，没人去替你的健康操心，除了你的家人对吧。很少会有人说你要不去动一动啊。甚至我觉得回来有部分原因——可以逃离北京的雾霾（笑）我觉得回来一年多后，鼻炎好多了。
### 后记

**D**: 很遗憾地说，在整理文档的时候，我感觉到这次活动并没有做得太好。首先是因为设备的原因，有几句对话已经无法分辨，最终只能无奈删去。

另一方面是我个人的原因，接近尾声的时候我已经被聊的内容和话题吸引，忘记了自己身为采访者，需要挖掘话题，控制节奏的本分。

明显可以感到，越是接近尾声的句子越短，对于话题的挖掘也没有深入。

但是，现场的气氛之活跃，是远远的超出了我的预期，让我感到虽然我能力有限，但是仍然希望能够继续将这个活动办下去。

也在这里厚着脸皮请各位朋友多多支持。如果有好的议题，或者希望参与到这个活动中的志愿者，请跟我联系。

[Yncoder 主页](http://yncoder.org/)

请使用链接转载本文，感谢支持。

**Comment by moreoronce** [comment]
羡慕自由职业
我也在努力

**Comment by nanmu42** [comment]
厉害了，祝顺利。

我也是远程，这样的工作好处和坏处都很明显。
