### ISSUE TITLE
2015.04月份聚会通知

### ISSUE THREAD

**Issue by gc87** [yncoder/yncoder.github.io#3]
时 间：2015-04-25 13:00:00 （本周六下午一点）
地 点：一二一大街、云南大学校园内——阳光咖啡
桌 号：包间2
形 式：圆桌讨论（不限于技术）
要 求：带着话题来

后 记：本次活动已圆满结束！参与的人员超出了预期，这里要感谢各位的积极参与，尤其要感谢云南桥接科技的支持。
我们活动的目的就是为了要产生联结，让每个处于孤岛的个人和团体连接在一起，产生更多的可能性。
ps：下一次将更加精彩。

**Comment by mytharcher** [comment]
先报上，不过晚上有事可能要早点撤。

**Comment by ghost** [comment]
报~

**Comment by ghost** [comment]
我帮群里的“月亮”姐姐报个名，她没有github帐号……预计2点左右到。

**Comment by bigzhu** [comment]
报名吧…话说人这么少
费用AA么？

**Comment by mytharcher** [comment]
@bigzhu 那当然是 AA，要不 zhu 总赞助也行，哈哈

**Comment by arlicle** [comment]
OK, 到了怎么联系？

**Comment by gc87** [comment]
@arlicle qq群，或者微信群可联系，周五会在这里更新桌号，到了可以直接找桌号

**Comment by arlicle** [comment]
可以加下我的微信然后拉我入群吗？微信号就是我的 github ID

**Comment by ghost** [comment]
我想问一下，能不能带比较严肃认真的话题来？

**Comment by gc87** [comment]
@ZhangRGK 多严肃认真？

**Comment by ghost** [comment]
我又来帮人报名了。

张利彬——原春城晚报技术总监，现在正在组建团队ing。

**Comment by gc87** [comment]
外边的桌可能坐不下，预留包间2，我13:00在那里等你们

**Comment by mytharcher** [comment]
我也代帮个律师妹子报名，很感兴趣。
