### ISSUE TITLE
络石软件设计招聘

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#31]
## 招人前先介绍自已

我们是[昆明络石软件设计](http://www.lorstone.com/)，初创公司。

技术主线: vue.js 全家桶 + tornado + postgresql

目前期望招**一位核心开发**以及一位以能留下来为目标的**实习生**，我们能提供：
- 轻松的氛围和自由的上班时间
- 有意思的项目

## 对实习生提供：
-  800-1500的实习补贴
- 十多年工作经验老师傅（我）的灌顶传功
- 在云南很难接触到的先进技术

## 对核心开发提供：
- 核心的地位，大饼不过多画了。初创有机会成本的优势，想想如果做大了......投资早，收益高
- 先进自由发挥的技术。虽然有一定的技术路线，但没有什么限制
- 7000-10000的待遇，大饼要有，温饱先行
- 轻松自由的合伙人待遇

## 希望找什么样的人
- 用mac/linux。如果你能在windows下把webpack和python开发环境搭建好那也行
- 会翻墙。嗯，用baidu会死人的
- 热爱技术，要热爱，要热爱
- 沟通能力较强
## 加分项
- 有一定的前端基础: html css js
- 用过git/github/bitbucket
- 有自已blog且还在更新

## 多说几句
对了，如果你是想弄个资历以去“大公司”，那过来没什么用，我们太小了，这资历无价值。
如果是想来入个技术门，在云南换个公司，也有点不合适，技术线和云南通常的IT公司差异有点大，如果你以后要去北上广或者自已freelancer那应该还ok。
希望有不得不呆在云南这技术贫瘠的地方，又真的追求下技术的同好能一起来做点有意思的事。

有意向的和我联系: zhuyifan@lorstone.com
qq: 51786189
微信: bigzhu

**Comment by geekrainy** [comment]
只要妹子，233333

**Comment by bigzhu** [comment]
汉子也可以的，不是只要妹子

**Comment by scriptfans** [comment]
离得好近……
