### ISSUE TITLE
2016 年年底小型非正式聚会

### ISSUE THREAD

**Issue by oldrev** [yncoder/yncoder.github.io#32]
介绍文字直接抄的 2015 年的：

> 该聚会源于“昆明开花者”群，旨在通过有关互联网技术和其他话题的交流分享，提升昆明本地较为落后的技术交流氛围，并借此机会建立一个长期交流分享的社区，以促进成员之间互助提高和资源共享。
> 
> 我们相信，每个开发者都是富有创造力的个体，即使在这块IT欠发达的土地上，我们也并不孤独。

本次活动是非正式的活动，暂时没有特定的讲师做主题分享，而是主要供大家聚会多聊聊家常，加加微信，反正就是一个务虚性质的聚会。

出于给群中【老革命[屠夫]】的老婆的咖啡店拉拉人气的私心，活动场地选择了学府路的 Soulmate 咖啡店。

各位有空参加的可在本 issue 下留言，若人数较多可包场，无场地费，饮品 8 折。

## 本次活动安排

* 时间：2016年 12月 25日（周日）下午 14:00
* 地点：学府路 Soulmate 咖啡店（虹山东路学府路交叉口，万科学府 2 期 18 号商铺，[戳这里看地图](http://j.map.baidu.com/hWoQH)）
* 内容：主题分享 + 书籍交换 + 自由交流
* 费用：各人自行消费即可。

**Comment by mytharcher** [comment]
赞，可以直接改成正式的嘛！+1

**Comment by bigzhu** [comment]
报名
能去就尽量去听一听咯

**Comment by zzdjk6** [comment]
报名~

我要8折~

其实以后『无主题』的活动，也可以办成 hackthon 哦~

**Comment by ghost** [comment]
周日下午要去亲子班，我周日上午去:)
咖啡馆有午饭供应吗？

**Comment by oldrev** [comment]
@ZhangRGK 如果没有可以叫外卖的

**Comment by gc87** [comment]
报名

**Comment by Daetalus** [comment]
报名，有点晚了。。。

**Comment by viest** [comment]
这属于前端还是？

**Comment by bigzhu** [comment]
@VikinDev 程序员聚会,没限定技术.

**Comment by viest** [comment]
@bigzhu 有群号吗？我加一个！

**Comment by gc87** [comment]
39615502
