### ISSUE TITLE
≈4年前端求职

### ISSUE THREAD

**Issue by kmfe** [yncoder/yncoder.github.io#36]
- 熟悉html/css/javascript
- 熟悉前端框架,处理器: jquery/easyui/ng1.x/vue2.x/sass
- 熟悉前端自动化工具: gulp/webpack
- 熟悉使用版本管理工具: git
- 略会nodejs,express+ejs+mongodb
- 了解java,略会php,会使用smarty/thinkphp

有大公司工作经验(EF，教育行业)，本人目前在上海，想回大云南，想家....
求推荐，求收留，有意者留言  😭
感谢 @ZhangRGK 提醒

**Comment by ghost** [comment]
这时候订阅 Org issues 提醒的优势就体现出来了。

留下联系方式~

**Comment by kmfe** [comment]
感谢各位了，耽误你们时间了，已经决定回老东家了，再次感谢 @ZhangRGK   锐哥赏识~，也感谢 @bigZhu 朱哥介绍工作，麻烦你~
