### ISSUE TITLE
2017 下半年聚会

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#42]
##  不写代码的时候干点啥

时间: 2017年9月9日 13:00 - 自便
地点: [soulmate 咖啡](http://map.baidu.com/?shareurl=1&poiShareUid=35a1273d5fbe6531d2f49e3d)
 
虽然身为程序员，但是，生活才是更重要的啦！

那么，各位在不工作的时候有怎样的兴趣爱好呢？

这一次聚会是轻松的 topic 主题分享，唯二要求：

1. 每人30分钟以内
2. 不触犯国家相关法律

以上，请各位报名。

p.s. 如果需要展示装备的请早一点点到布置一下自己的站台 XD

各位报名的时候请附上自己期望的时间，时间将会在 8月25日根据投票确定

**Comment by ghost** [comment]
+1
9月9日
大概会来安利一堆游戏和书吧。

**Comment by yxyufo110** [comment]
233

**Comment by dianyiqe** [comment]
可惜不在云南 发自网易邮箱大师 在2017年08月21日 16:59，yxy 写道： 233 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zzdjk6** [comment]
9月10日

没有什么可以分享的...

**Comment by leebo** [comment]
+1
9月9日  9月10日 都可以
认识 一下圈里的朋友 总算找着队伍了

**Comment by mytharcher** [comment]
时间都 ok，并将继续私人赞助微量程序员桌面专用木制品，奖品规则由主持人确定 ^_^

**Comment by woondroo** [comment]
9/10随意

**Comment by wst1620125** [comment]
报名 9

**Comment by oldrev** [comment]
报名吧

**Comment by scriptfans** [comment]
嘿嘿嘿，带我儿子来围观

**Comment by gc87** [comment]
来不了，那会儿还在加班吧应该。

**Comment by gc87** [comment]
+0 
来不了，那会儿还在加班吧应该。

**Comment by ttop5** [comment]
+1

**Comment by christmasjason** [comment]
羡慕
