### ISSUE TITLE
Clojure 学习小组的成立

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#43]
大家好，除了在QQ群里成为传说，我又立下了更伟大的目标，就是

### 在 issues 列表里屠版

社区里应该有不少小伙伴都有关于『Clojure』的书在吃灰吧。

愿意再尝试一下的伙伴们可以回复本帖，让我们一起从实际的编码中学习 clojure。

**Comment by ghost** [comment]
回帖格式参考:

我对 Clojure 挺感兴趣的……主要喜欢的是_______方面。

我想做个________东西。

**Comment by bigzhu** [comment]
围观 + 消灭 0 回复.

**Comment by danielliao11** [comment]
我对Clojure挺感兴趣的……主要是纯函数和并发方面。

想要拿来重构 IvyEnglish 加速产品迭代。

**Comment by gc87** [comment]
之前的一个项目中，由于个人开发经验问题，没有小心处理全局变量的问题，导致数据发生（灾难性的）错乱，所以对“不可变性”以及“软件事内存（STM）”产生了期待。我想做个梦（逃
