### ISSUE TITLE
准备 Clojure 开发环境

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#44]
## 安装 Oracle Java

这个就不详细说了，安装 Java 的教程实在是太多了。

同时别忘了配置好环境变量。

## 安装 lein

[leiningen](https://leiningen.org/) 是 Clojure 的项目管理工具。

简单的说就是 gradle 之于 Java 的感觉

### mac
~~~
brew install leiningen
~~~

### linux

跟随 leiningen 首页的指示安装即可

### terminal 科学上网特别麻烦的 linux

- 去 github 上下载最新的 release: [地址](https://github.com/technomancy/leiningen/releases);
- 创建目录 `~/.lein/self-installs`
- 把下载下来的 zip 文件重命名成 .jar 放到 self-installs 目录下 `mv leiningen-<version>-standalone.zip ~/.lein/self-installs/leiningen-<version>-standalone.jar`
- 把官网的脚本保存成 /usr/local/bin/lein

## 使用 lein

~~~
lein repl
~~~

~~~
lein new my-project
~~~

## 编辑器

- 编辑器推荐: VSCode 并且安装 Clojure 插件
- IDE推荐: [cursive](https://cursive-ide.com/)

Emacs 和 Vim 大神我就不多做推荐啦

以上就是入门搭建开发环境的过程。

对 Clojure 感兴趣的同学请给我留言支持。

*顺便邀请本群最熟悉 Clojure 的纯哥( @gc87  )推荐一些入门书籍*

**Comment by gc87** [comment]
https://book.douban.com/subject/26789422/
https://book.douban.com/subject/26548501/

读了这两本就能写程序了，另：我不是最熟悉的，我算入门水平，共同学习，共同进步。

**Comment by gc87** [comment]
http://www.luminusweb.net/

clojure的web framework

**Comment by gc87** [comment]
clojure web开发三大件
ring https://github.com/ring-clojure/ring
compojure https://github.com/weavejester/compojure
selmer https://github.com/yogthos/Selmer

clojure restful
liberator http://clojure-liberator.github.io/liberator/

**Comment by gc87** [comment]
clojure 开发推荐使用cursive + idea，个人授权，每六个月重新申请一次，等于完全免费使用。
cider的问题在于cpu资源占用率太高。

**Comment by danielliao11** [comment]
纯哥给力

**Comment by arlicle** [comment]
工具用Emacs 或者 LightTable
