### ISSUE TITLE
Youtube 新版使用了 Web Component, 这货还活着?

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#46]
https://twitter.com/HenrikJoreteg/status/902644511704154113

![image](https://user-images.githubusercontent.com/489815/30517334-8e4ee2aa-9b8e-11e7-8ec0-fd1b911a672e.png)

浏览器支持的 Web Component 是不是以后能把 React VueJs 这些虚拟 component 干掉了? 不过进度太慢了, 感觉坑都被占完了.

**Comment by mytharcher** [comment]
等到 Web Component 的时候前端又要更新，真不想再换技术栈了。看到 React 刚好岔个话题：[如何看待百度要求内部全面停止使用React / React Native?](https://www.zhihu.com/question/65437198)，大厂们这是要开始造轮子大赛的节奏。所以还是期待 Web Component 早点来吧。

**Comment by ghost** [comment]
我理解的 web-compoments 主要是两个部分

1. 允许开发者实现复杂自定义组件
2. 自定义标签实现强语义化

这些需求已经由 react(包括 ng 和 vue) 实现了。

等标准落地了框架换一下实现的内核就好，前端并不需要学一套新框架啦。

顺便纪念下 Polymer……

**Comment by ghost** [comment]
@mytharcher 这个新闻应该是针对 FB更换 react 开源协议的应对措施吧。B厂现在想要造有影响力的轮子感觉有点晚了……
