### ISSUE TITLE
怎么全局的监听 fetch 事件?

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#47]
用 XMLHttpRequest 发起 ajax 请求时, 可以这样做

```javascript
const xhr = XMLHttpRequest
function highjackAjax (startHandler, endHandler) {
  xhr.prototype.send = function (...args) {
    startHandler()

    this.addEventListener('abort', endHandler, false)
    this.addEventListener('readystatechange', () => {
      if (this.readyState === 4) {
        endHandler()
      }
    }, false)

    send.apply(this, args)
  }
}
```

可是 fetch 根本找不到怎么监听全局的 fetch 事件

https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent 这里 `addEventListener('fetch',` 只能在 ServiceWorker 下用

这么土?  没有优雅的方式捕捉到? 

只能我自已再包一层了么?

**Comment by ghost** [comment]
没试过，提供个思路。

Fetch 返回的总是一个 Promise，那只要给  request, response 加上 Proxy 就可以了。

另外推荐用 axios。

就算监听了全局的 fetch 事件也不能 cancel……

**Comment by bigzhu** [comment]
想实现一个独立的进度条组件, 这样的方式有点达不到目标.

另外 axios 有什么好处?

**Comment by ghost** [comment]
可以 cancel
可以 interceptor
可以创建独立的实例应对多种情况，比 fetch 好用太多了……

**Comment by Vanessa219** [comment]
sw 中有 self.addEventListener('fetch', event => {})
