### ISSUE TITLE
社区里有刷freeCodeCamp的么

### ISSUE THREAD

**Issue by ysfscream** [yncoder/yncoder.github.io#51]

**Comment by nanmu42** [comment]
有～
刷了300多一点。

**Comment by ysfscream** [comment]
@nanmu42 哇~ 终于感觉有个同伴了 想找点一起刷过 FCC 的人 以后有机会弄点 FCC 的那种 coffee & code 的活动在昆明 
貌似 看到你的 github 发现你今天活动好像坐在我前面😂

**Comment by nanmu42** [comment]
😄 幸会！
FCC有昆明社区的，但是线下活动一直没做起来。
你可以加fcczhongguo让他拉你到微信群。

**Comment by ysfscream** [comment]
哈哈哈哈 竟然有! 但是我加了他 不回我 😅

**Comment by mytharcher** [comment]
FCC 还有本地社区啊，这种组织可以拉到 Github 这里一起玩耍嘛，需要开个仓库都行哈！

**Comment by oceanlvr** [comment]
请问可以给个传送门捏
我现在也是一个人刷fcc

**Comment by nanmu42** [comment]
邮件联系，我拉你。 :smile:

**Comment by oceanlvr** [comment]
@nanmu42 657531018@qq.com
麻烦您了

**Comment by bigzhu** [comment]
你们在中国版刷么？

这货不是硬分叉，撕逼得很厉害么

**Comment by oceanlvr** [comment]
@bigzhu 两个都有刷，话说为什么会撕起来啊

**Comment by ynzkai** [comment]
刷过一哈，感觉有点无聊。。。

OuYangXun <notifications@github.com> 于 2018年12月4日周二 上午10:00写道：

**Comment by ysfscream** [comment]
@nanmu42 哈哈 也拉拉我 894402575bt@gmail.com
@oceanlvr 兄弟阔以加个微信么 😃

**Comment by nanmu42** [comment]
这么多啊，兄弟们直接加微信吧：

```js
atob('cGVhY2VuYW4=')
```

**Comment by oceanlvr** [comment]
> atob('cGVhY2VuYW4=')

加您了
