### ISSUE TITLE
生活不止眼前的代码，还有灵魂和技术的升华 

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#52]
# 生活不止眼前的代码，还有灵魂和技术的升华 

#### 2017年下半年社区分享活动

> 除了编程、开发、敲代码、改BUG，程序员们也都需要广泛的交际。这样不但开拓眼界，共享知识分享经验，还能净化心灵，寻找知音和靠谱的搭档，结交人脉，顺便学会吹牛逼。
> 作为程序员，我们不能只一头扎进自己擅长的语言、技术不问世事，也不能沉迷于各种派别的新潮流浅尝辄止。我们要像马云的电影《功守道》里那样，与各个技术流的大咖进行切磋交流，才能领悟到这个不断变化的程序员世界的终极奥义。
> 现在有这么一群程序员，上天入地，无所不吹，还请了多位大咖来坐阵，比如包括比特币和区块链等最新技术流的多位巨侠，准备与大家切磋程序员世界的新态势和技术新发展。
> 干货！干货！我们只为大家提供真正的干货，我们的口号是：拒绝黄赌毒，拒绝非干货！
> Talk is cheap, show me the code! 

#### 本次活动由[昆明云链科技](http://jobs.51job.com/all/co4234999.html)发起, 请点链接查看招聘信息.

【精彩内容预告】

时间：11月25日 下午13:00
地点：五华区学府路690号金鼎科技园17号平台C座一楼猪八戒活动厅[点击查看](http://j.map.baidu.com/wewWj)

### 主题分享：

- ["区块链&互联网技术灵魂交流"](http://yncoder.org/assets/presentation/2017-11-25/block-chain.pptx) by [@一休](https://github.com/woondroo)
- ["Another side of Programming Language"](http://yncoder.org/assets/presentation/2017-11-25/ASOPL.pptx) by [@风雪](https://github.com/gc87)
- "CRUD boy 的逆袭" by [@老革命](https://github.com/oldrev)

### freetalk

- [DevOps](http://yncoder.org/assets/presentation/2017-11-25/DevOps.key) by [@ZhangRGK](https://github.com/ZhangRGK)

tips: 

- 活动是开放式, 不需要报名也可以参加;
- 但依然希望大家可以跟帖报名, 方便组织者统计人数, thx.

**Comment by mdhh1988** [comment]
+1

**Comment by ttop5** [comment]
+1 :neckbeard:

**Comment by ysfscream** [comment]
@ttop5 带上我 + 2

**Comment by leebo** [comment]
+1

**Comment by oldrev** [comment]
报名

**Comment by mytharcher** [comment]
+1

**Comment by scriptfans** [comment]
plus one

**Comment by williamwa** [comment]
+1

**Comment by yxyufo110** [comment]
+1

**Comment by haishangshijie** [comment]
+1

**Comment by superkam** [comment]
+1

**Comment by gc87** [comment]
+1

**Comment by ghost** [comment]
@Myu1533 @ttop5 @ysfscream @leebo @oldrev @mytharcher @scriptfans @lancehub @yxyufo110 @haishangshijie @superkam @gc87 
地点改成了17号平台的猪八戒活动厅, 请点开地图查看.

**Comment by danielliao11** [comment]
+1

**Comment by thomasgazzoni** [comment]
+1

**Comment by soullzy** [comment]
+1

**Comment by nanmu42** [comment]
+1
