### ISSUE TITLE
大家最近在学什么

### ISSUE THREAD

**Issue by yasuoganliang** [yncoder/yncoder.github.io#53]
大家最近在学什么

**Comment by ynzkai** [comment]
算法、数学分析、编译原理、swift、iOS

**Comment by kentzhang-geek** [comment]
搞定Qt+Web+OSG这套基础框架，估计就会集中精力研究渲染了，Realtime Rendering之类的。光线追踪暂时应该不会入手。

**Comment by nanmu42** [comment]
Golang.

KentZhang <notifications@github.com>于2018年3月15日周四 上午11:20写道：

**Comment by kentzhang-geek** [comment]
现在在看实时渲染那本书咯，原版看着挺费力的，看到150多页讲透明那里了

**Comment by bigzhu** [comment]
Flutter  
刚开发完一个给自己用的学英语的 APP 用的很爽

**Comment by CNDAXI** [comment]
python，wireshark，英语，数据分析，网络安全。
