### ISSUE TITLE
在实战中学习 Clojure

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#56]
在对 Clojure 的概念和语法有一些了解之后, 就可以开始用 Clojure 写代码啦.

这里推荐一个网站 [4Clojure](https://www.4clojure.com/) 可以应证自己对 Clojure 的理解是否正确.

同时还有这个 [Clojure 语法](https://wizardforcel.gitbooks.io/clojure-fpftj/) 当做工具书用.

最后祝各位武运昌隆 (笑)

**Comment by scriptfans** [comment]
上车了
