### ISSUE TITLE
看到一个本地政府+腾讯背景的旅游项目招聘，国资商城的同学要不要来谈谈看法

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#58]
> [“一部手机游云南 ”3月1日亮相 腾讯云南今起遍撒英雄帖](https://view.inews.qq.com/a/PLY201801120120080D)

又一个政府主导的 IT 项目，不同的是这次有腾讯的背景。1 月 12 日发布，3 月 1 日要“亮(shang)相(xian)”，刨除春节只有一个月多的时间，不知道大家什么看法？这会是本地 IT 从业者的新机(shen)会(keng)么？

**Comment by bigzhu** [comment]
有人找我做这个的外包....然后我没接, 囧

感觉错过了一笔大生意啊

**Comment by kentzhang-geek** [comment]
腾讯不是在昆明招人么，感觉这是一波操作

**Comment by nanmu42** [comment]
这个项目已经开始运营了。
富滇银行貌似还是合作伙伴。

KentZhang <notifications@github.com>于2018年3月15日周四 上午11:18写道：

**Comment by bigzhu** [comment]
我知道的好几个人已经进去了..貌似待遇开的还不错.

ios 可以搜 游云南 装 app 看..

android 的还没发行.

个人来说并不是很喜欢这种政府牵头的 IT 项目, 难做成.

**Comment by mytharcher** [comment]
小程序倒是搜到了：一机游云南。然而。。。

![screenshot_2018-03-15-13-52-01](https://user-images.githubusercontent.com/525658/37446493-36d3b44a-2858-11e8-97b0-84ed8829509a.png)

**Comment by bigzhu** [comment]
哈哈, 简直了, 果然很有政府 IT 项目的风格

**Comment by CNDAXI** [comment]
都学过，但是都不精
