### ISSUE TITLE
云大 ComeTree 与 Yncoder 合作交流活动

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#64]
![image](https://user-images.githubusercontent.com/525658/42209671-d4148678-7ee1-11e8-86f4-0a47931656cd.png)

本次 Yncoder 作为挂名组织受邀参加 ComeTree 的技术交流活动，欢迎社区的小伙伴们一起来交流！

* 时间：2018 年 7 月 7 日 下午 13:30
* 地点：云南大学（本部）北门 云大科技创业园负一楼报告厅

**Comment by nanmu42** [comment]
Wow~

**Comment by soooooot** [comment]
还有海报！！

**Comment by viest** [comment]
666666

**Comment by scriptfans** [comment]
最近忙不过来啊，倒是想来，唉

**Comment by xdliuyong** [comment]
👍

**Comment by mytharcher** [comment]
活动图片

![image](https://user-images.githubusercontent.com/525658/45528879-fc817780-b814-11e8-9314-4ee0cd5ea568.png)

![image](https://user-images.githubusercontent.com/525658/45528868-eb386b00-b814-11e8-89b1-e9b1d6e8f761.png)
