### ISSUE TITLE
【黑名单】PHP 面试冒用Laravel-china “leo” - 朱国强

### ISSUE THREAD

**Issue by viest** [yncoder/yncoder.github.io#65]
此人冒用Laravel-china管理员“leo”，为了进一步验证，向他索要了 Github ID ，和 Laravel-china 管理员 leo 的 Github ID 一致；目前已经和 Laravel-china 社区确认此 ID 为假冒；目前此人还在找工作阶段，请各位面试单位留意！
![screenshot_20180725-162803](https://user-images.githubusercontent.com/14308107/43188998-1b579910-9028-11e8-9f8e-6883d87f3a3f.jpg)

**Comment by nanmu42** [comment]
大佬火眼金睛。

**Comment by mytharcher** [comment]
实在不知道该加什么标签。。。

**Comment by bigzhu** [comment]
哈哈，你这么愤怒～

我对于他今天没来，没面到他还挺遗憾的

**Comment by dotatata** [comment]
竟然还有这种事儿

**Comment by viest** [comment]
此人惯犯，已经有人在昆明面他的时候，冒充 overtrue 了

**Comment by yanxiangrui** [comment]
😄厉害啦

**Comment by szy0syz** [comment]
上周 朱师 投我司了，明明我们招JAVA，他一个PHP来，真想会会他。

**Comment by bigzhu** [comment]
啥，这人姓朱。家门耻辱…

他连简历都是胡乱投的么
