### ISSUE TITLE
出一个全新的 kindle paperwhite

### ISSUE THREAD

**Issue by ttop5** [yncoder/yncoder.github.io#68]
`已售出`

全新未开封。公司发的礼物，由于自己手里已经有一个了，所以打算出手。
出手价格：`￥858`，可小刀。为节约双方时间，能当面交易者优先哈。
有意者可加微信：
![wechatimg55](https://user-images.githubusercontent.com/9512362/45274425-01c78500-b4ea-11e8-89d4-eec2663b365e.jpeg)

![wechatimg53](https://user-images.githubusercontent.com/9512362/45274237-1fe0b580-b4e9-11e8-84ff-c318466def46.jpeg)
![wechatimg54](https://user-images.githubusercontent.com/9512362/45274238-2111e280-b4e9-11e8-80f6-b020afb9bfde.jpeg)
![wechatimg52](https://user-images.githubusercontent.com/9512362/45274239-22dba600-b4e9-11e8-9efc-947d9d9dd866.png)

**Comment by ttop5** [comment]
![fdd0621949c352dd86da904129e98c07](https://user-images.githubusercontent.com/9512362/45274765-7e0e9800-b4eb-11e8-957d-efa491c0fde5.jpg)

**Comment by nanmu42** [comment]
哪个公司？（滑稽）

**Comment by bigzhu** [comment]
在昆明? 同问是哪个公司哦?

**Comment by ttop5** [comment]
@nanmu42 @bigzhu 公司是EMQ哈，在昆明有个小的研发部。

**Comment by ysfscream** [comment]
@ttop5 不来上班改 BUG 竟然在家卖 Kindle？🌚

**Comment by ttop5** [comment]
@ysfscream :sneezing_face: 哈哈哈

**Comment by zibuyu1995** [comment]
已截图给英姐。😂

**Comment by ttop5** [comment]
已售出，感谢平台和各位。:smile:
