### ISSUE TITLE
MacBook Pro with Bar (2018) 的槽点，顺便出一台 MacBook Air 11 (2012 later)

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#74]
纠结了很长时间还是选了带 Bar 的 MBP 13 (16G) 升级，先说表扬的部分：

1. Bar 的好处暂时还没完全体现，但我总觉得应该会有的。
2. 四核性能的确强，webpack 编译还没来得及切换浏览器就完成了，但也可能是我忍渣性能的 MBA 太久了。
3. 4 个 Lighting 3 插口的确方便，不过还没插满，等其他设备升级完 USB-C 估计要很久，还是要买个扩展坞。

好了，开始槽点：

1. ESC 在 Bar 上是虚拟键，导致按起来毫无感觉，根本无法得到物理反馈，Bar 很好，但留这一个实体键会更好，我觉得 vim 党应该会有更深的体会。
2. 没有电源键了，没法用组合键进入睡眠锁屏，于是只好在 Bar 上设置一个睡眠键，但很少的情况下会误触，体验不太好。
3. 键盘方向键的左右两个键太大，理解是为了视觉设计和和谐统一而加大成全键大小的，但是实际上盲打的时候无法通过间隔区域直接摸到上下键，经常误触或者要看键盘找键，非常不爽。这点在单独卖的 Magic KeyBoard 2 上也存在，实在无解，看来机械键盘党才能避免。
4. 盒盖情况下居然不能用 USB-C 给手机充电，盒盖到休眠时间后给 USB-C 的供电就自动断了？？？因为经常都背着电脑，所以我是从不用充电宝的人，背包里的电脑不能给手机充电简直无法理喻！如果是我使用的姿势不对的话麻烦告知。

苹果真是为了赚钱故意设置这么令人纠结的性价比，买 2017 款是要差一些，但性价比在某种程度上是要高一些。我是本着不折腾的态度希望买一个本作为主力机再用 6~8 年的，真希望这价格对得起我的期望，毕竟现阶段想用带 MacOS 的笔记本真没的选，只能交信仰税了，台式机我一定毫不犹豫的黑苹果。

最后顺便试着出一台替换下来的 MBA：

* 型号 A1465 2012 later，11 寸，4G 内存。
* 已更换创见 256G SSD，原装 128G SSD 被我买了转接口在某 PC 上继续服役，要换原装的也行。
* 中间电池自己买淘宝的更换过一次，至今仍能坚持 3 小时开发或 4 小时网页浏览。
* 购买了第二个 45W 电源，因为原装的线皮到处裂开缠胶布勉强用，所以都是固定家里放一个公司放一个不用经常拔也不用背。同时送一个 DP 显示器转接头，可转 HDMI/DVI/VGA。
* 【缺陷】当年换新包的时候不小心摔在地上过，正面两个角略有缺口，但不影响盒盖和使用，底面（D 面）有几条比较深的刮痕，只关注配置的话其实无所谓，回头上图。

![51010348-eac79b00-158e-11e9-994d-4fd82d4f4514](https://user-images.githubusercontent.com/525658/51010765-aa691c80-1590-11e9-9410-f78b2476708a.png)

系统参数

![mvimg_20190111_102834](https://user-images.githubusercontent.com/525658/51009954-15185900-158d-11e9-9684-4401af8d39e0.jpg)

A 面

![mvimg_20190111_102907](https://user-images.githubusercontent.com/525658/51010227-565d3880-158e-11e9-8cd7-2297a327cb04.jpg)

D 面

![mvimg_20190111_102930](https://user-images.githubusercontent.com/525658/51010127-e484ef00-158d-11e9-96a0-f2ef8b14b923.jpg)

B/C 面

![mvimg_20190111_102846](https://user-images.githubusercontent.com/525658/51010155-08483500-158e-11e9-9347-c3d139e4ad41.jpg)

右侧边角缺陷

![mvimg_20190111_102852](https://user-images.githubusercontent.com/525658/51010167-18601480-158e-11e9-8b7c-b8eff22678aa.jpg)

左侧边角缺陷

![mvimg_20190111_102859](https://user-images.githubusercontent.com/525658/51010181-24e46d00-158e-11e9-8bf0-86f5b54f3c76.jpg)

左后侧小缺陷

总之这台 MBA 其实还是很坚挺的，要不是 4G 内存太小我开发开的程序太多的话，再战两年我感觉也是 OK 的。如果开的程序不多，并感觉不到什么卡顿。而且依然是最轻便的 MacBook 之一，而且说实话并没觉得 Retina 清晰带来多大变化。可惜家里没人用电脑了，所以还是决定出给有需要的人。价格可以参考淘宝同配机型，暂定 3000，可小刀，尽量同城面交。

**Comment by scriptfans** [comment]
新款蝶式键盘才是最垃圾的……

**Comment by mytharcher** [comment]
@scriptfans 我居然觉得还好，除了声音不够干脆，哈哈。

**Comment by mytharcher** [comment]
已出，谢谢！
