### ISSUE TITLE
程序员最佳健身实践

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#75]
套程序员的名来说事, 容易引起反感. 本想用"长期伏案者", 但总觉得不足以表达典型长期熬夜加班把自己身体搞垮的严重状态, 所以还是用程序员好了. 何况本身就是把自己身体搞垮的老程序员没错.

## 本人情况

"老程序员的出路" 这问题有个答案是: "把身体弄好点, 别把多年用身体换回的钱又交给医院去了, 猝死了就更亏了." 深表同意.

大部分人要么瘦如猴, 要么胖如猪, 正好两个状态都经历过.

2005 年开始工作时候, 长期 50KG 左右, 180 身高, 直接的后果就是单身好多年.

![](https://ws3.sinaimg.cn/large/006tNc79gy1fz45pfya5mj307p0fkwer.jpg)

2016 年自己组团队做外包时候, 恍然发现已成了油腻的中年胖子. 胖子的图就不贴了, 太油腻.

健康状况一塌糊涂. 2015 年辞职, 因为过于拼命给前东家鞠躬尽瘁, 从上到下/从里到外没几个地方是健康的: 白发增多, 近视干眼症, 鼻窦炎, 咽炎, 颈椎肩膀严重劳损, 心悸心绞痛, 胃溃疡, 鼠标肘, 腰椎膨出腰肌劳损, 痔疮严重, 略过..., 小腿经常抽筋, 脚关节长期扭伤红肿疼痛(疑似痛风)

体检尿酸超级高, 其他血液指标处于及格线线边缘. 长期失眠神经衰弱, 经常低血糖. 
每两星期, 鼻窦炎发作一次, 疼到连续几天整夜无法入睡. 一年至少大感冒一次, 持续 2-3 周, 每次都烧到怀疑自己挺不过去了.

总结一下: 一塌糊涂, 很庆幸当年没有猝死.

## 现在的情况

80kg 180, 穿衣显瘦, 脱衣很壮. 

白发不见了, 近视改善眼睛不干了, 鼻窦炎咽炎大幅缓解, 空气太差偶尔不舒服时候顶多睡一觉就好. 颈椎还是不好, 毕竟对着电脑时间依然很长. 心悸心绞痛再也没有了, 体检心脏比常人还健康. 消化能力超强, 痔疮基本不犯了, 略过那里超强, 腰椎膨出腰肌劳损基本痊愈, 小腿抽筋再也没有了, 关节扭伤红肿没有了.

尿酸降到正常值范围(不治之症就这样痊愈了?), 睡眠质量良好. 低血糖基本没了. 快2年没发烧了.

## 健身经历

很多年前就一直办有健身卡, 也花费上万请过教练, 效果真不行, 弯路走了太多, 真正上道反而是自己琢磨自己练开始的, 到现在不到2年. 目前三大项目也就基本能搞动自己体重的重量, 和肌霸大佬们比起来差的太远, 只能是健身入门, 不过已经能达到修复身体, 不要送钱给医院的目标了.

程序员走上健身之路, 还是有些区别和需要注意的点, 把这个经验分享出来, 希望能有用.

## 吃的方面

吃要算4分, 请教过大肌霸教练吃的问题, 但是大肌霸们对于我们这种入门渣, 总是带有不屑, 让正常吃, 每次训练完多吃一个蛋就好了. 

这个算是最大的弯路, 导致艰辛痛苦的训练, 却没有什么效果, 非常糟糕.

关于吃的写过好几篇, 看公众号就可以了. 

简单来说, 就是在自己消化能力范围内, 吃尽量多的高蛋白. 

长期加班, 经常点个外卖快餐什么的, 程序员都是长期营养不良的, 本人是吃了好久的高蛋白饮食, 慢慢才把多年的亏空补了回来. 所以实际上我们需要比大肌霸教练吃的还好才行, 毕竟亏空了很多年. 可以先吃好点, 补充够足够的蛋白, 再开始健身.

## 康复期 

国内容易教条, 医生这样, 健身教练也是一样. 不要以为他们很专业, 很多教练就是教条的按照规范来授课, 不知道什么叫对症下药, 不知道什么叫个体差异. 

能根据你身体对应调整训练计划的好教练也许有, 但很难碰上.

所有教练, 都喜欢4组每组15个的来(估计书上这样写的), 但是按这个方式来, 非常的糟糕, 每组15个做的痛苦不堪, 每次练完, 肌肉恢复不了, 甚至长期属于僵痛状态, 教练顶多和你说拉伸下, 拉伸下... 结果越练越衰弱.

持续练了半年, 也没什么效果, 每次上课都过于痛苦, 还要经受无形的鄙视, 对健身都有了莫大的恐惧感, 磨磨蹭蹭的再也不想去上课了, 估计大部分的人都是一样的经历吧.

回忆一下, 当时的肌肉水平是略低于普通人的, 长期坐着敲敲键盘, 说是手无缚鸡之力也没错, 胳膊和身都是软趴趴的肥肉, 摸不到肌肉.

这也没什么可羞耻的, 长期没有运动, 长期加班熬夜, 肌肉感觉退化的差不多了, 体能也很差, 这种情况, 很明显不适合健身课上那种教条的训练安排, 经常练完心悸和低血糖, 其实很危险.

开始的这段时间可以看做康复期, 基本的力量还有, 但是耐力很差, 能量供给和代谢也很差. 所以给自己的安排大约是这样:

依然还是4组, 但是每次只做 3-4 下. 3-4 下和 15 下比起来, 心理负担都要小得多, 咬咬牙也就过去了, 因为负担小, 也更愿意用更大的重量, 而不会想着: "用轻重量, 留余力, 毕竟要做 15 个", 更大的重量也更有效的刺激了肌肉的苏醒和复苏.

仔细观察身体的状态, 训练途中, 一旦出现头晕, 心悸, 心慌的状态, 立马停止训练, 回去好好休息, 而不是咬牙坚持训练. 因为身体长期优先供给能量给大脑, 根本不适应要为肌肉供给和储备那么多能量, 需要给身体一个调整的时期.

大约 1-2 个月这个阶段就过去了, 如果再长一些也没关系, 程序员健身初期真的得把自己当做康复期的病人, 没必要觉得有什么不好意思的. 那些大肌霸每天坐上十多个小时, 持续十多年试试?

## 体态纠正

度过康复期以后, 很容易狂妄自大, 开始上大重量. 但是程序员普遍体态就有问题, 一不小心, 轻则练的肌肉不均称, 重则颈椎腰椎膝盖受伤, 残废瘫痪不至于, 但是受伤几次也就练不下去了.

为何说程序员更容易受伤? 看看我们的工作体态.

![](https://ws4.sinaimg.cn/large/006tNc79ly1fz3s8dymd1j307e059jrc.jpg)

大部分的程序员都是是脖子前倾, 含胸圆肩, 核心肌肉羸弱, 背肌松弛无力, 盆骨前倾, 腰肌劳损. 反正本人全包含了, 这样的体态如果上了重量练习, 非常非常危险.所以要优先纠正体态. 我是受了几次伤, 走了弯路的.

基本上一开始体态都是左边这样的:

![](https://ws2.sinaimg.cn/large/006tNc79ly1fz3s7nqw56j307j056dfo.jpg)

引体向上, 皇者动作, 安全而且对纠正体态事半功倍.

宽臂靠胸引体, 也就是正握宽臂, 脖子后缩, 挺胸用胸去尝试碰杆的引体, 不要摇不要甩. 引体的教程知乎上非常多了, 这里不细说了.

![](https://ws1.sinaimg.cn/large/006tNc79gy1fz44nphzutj30f20auq3j.jpg)

这个动作做对的话, 一次性纠正了上面说了程序员常见的那些体态问题. 做的时候注意脖子后缩, 压下巴, 挺胸, 背部发力, 核心绷紧, 脚尖绷直.

安全是指, 这个动作什么人来做, 都很难做的不标准. 双手拽住杆子把自己拉上去, 对人的身体构造是再自然不过的复合姿势了. 从猴子开始就不知做了多少次了, 记住上面说的要点, 效果会更好.

普通人一个标准引体做不起来的太正常了, 一开始我顶多做半个, 所以起不来很正常. 辅助入门教程很多了, 健身房也有引体助力器, 这个动作长期坚持下来, 进步很快的.

前公司办公室有引体器械, 曾经拼过每天 100 个引体一段时间. 

这个完美的纠正动作也能让人感觉更阳光, 健康. 程序员经常给人一种猥琐的感觉, 很多时候是因为姿态不好导致的.

还有很多其他修正体态的练习, 这里不细说了.

## 减少痛苦指数

一说健身, 好像就是一个艰难艰辛苦痛不堪的过程. 每每都是需要深呼吸, 鼓起勇气, 去上一次, 练得全身酸痛. 第二次肝都是颤的, 各种思想斗争, 结果去了健身房, 跑了个步, 洗了个澡就回来了. 慢慢的就变成了健身房最优质的客户: 出钱办了卡基本不去.

没必要练这么猛, 跟着教练上课的时候, 经常全身酸痛, 手臂都抬不起来. 心中还窃喜, 觉得效果好了好...会持续疼上一个星期, 第二次上课雪上加霜, 肌肉力量没有增长, 长期僵硬疼痛. 要不是花钱上着课早他娘的放弃了, 太痛苦了. 一直以为健身就非得那么苦, 其实不是的.

后来自己练习的时候, 痛苦指数被降低到 0 甚至是负的, 因为每次练完分泌的多巴胺, 还让自己觉得阳光灿烂人生美好.

几个要点:

做好热身, 跑步机上快走5分钟. 不要长时间慢跑, 除非你不想要膝盖了. 而且长时间有氧是非常痛苦的, 别干这蠢事.

不要做耐力训练, 多次数的耐力训练到后面是非常非常痛苦的, 手臂都酸疼的不行了, 还要坚持, 能不痛苦么? 所以耐力训练属于痛苦指数奇高而效果低下的方式.

不要做短间隔训练, 很多训练安排, 休息间隔非常短, 30s 左右. 简直有病, 这个方法的理论是要在力竭的短时间完成多组才有效果, 这个和耐力训练没啥区别, 痛苦指数奇高效果低劣, 大部分教练也是按照这个方法来的. 

让发动机在缺油的状态下运转, 能不痛苦么?

建议间隔至少 3 分钟以上, 5 分钟以下, 做完以后一组以后, 血液会充到肌肉里为其补充能量, 需要等完全充满能量以后, 再做下一组, 充血的肌肉会比之前更有力. 

不要练到让肌肉长期酸痛. 用上面的训练方法, 第二天第三天恢复期的时候, 基本没有出现过疼痛, 比较明显的是酸酸涨涨, 有点发痒. 这其实是明显的生长恢复感, 尤其在练胸大肌的时候这感觉特别明显, 羞羞的... 如果有疼痛感就练别的地方, 完全不疼再开始下次训练.

注意休息, 3分练, 3分休息, 4分吃. 如果熬夜加班或者失眠睡不好, 或者有段时间突然状态不好, 就暂停训练. 别干什么咬牙坚持的蠢事.

所以最终有点成效, 肌肉增长最快的时期, 就在这种愉悦的每次很享受, 毫无痛苦的训练过程中实现了. 有了运动习惯, 一段时间不动, 肌肉还会发痒, 提醒你该去动动了.

## 逆金字塔训练

在前一篇[健身训练计划](http://www.bigzhu.net/blog/%E5%81%A5%E8%BA%AB%E8%AE%AD%E7%BB%83%E8%AE%A1%E5%88%92/)里面有详细说明, 这个和初期的康复阶段有异曲同工之处. 好处是在于隔一天训练一次, 并且每次只需要 1 个小时左右的训练时间. 毕竟还得花很多时间去工作学习写代码, 这种方式耗费的时间短, 并且效果还非常非常的好. 

基本方式学习的是 Greg O'Gallagher 的 [Kinobody](https://www.youtube.com/channel/UCtBw4N4-EiaAqK9TvZGlGDw) 的方法, 除了绝食不赞同, 其他方法都挺好的. B 站有 up 主做了翻译[这里](https://www.bilibili.com/video/av34806120)还有[这里](https://www.bilibili.com/video/av34961181), 还有很多, 自行找了看吧. 具体训练计划就不详细说了, 各人可能有差异, 各自总结. 健身的细节说起来就太多了.

2019 年经济下行, 世道艰难, 但至少我们可以努力使自己有个健康的身体. 

2018年3月份的状态:

![](https://ws4.sinaimg.cn/large/006tNc79gy1fz45rz8a6ij309g09gq38.jpg)

2018年7月份状态, 因为特意增肥, 很肥...

![](https://ws2.sinaimg.cn/large/006tNc79gy1fz45t10ab9j30fr0btjs1.jpg)

无论如何, 祝愿大家在新的一年里, 能拥有一个强健身的身体吧!

**Comment by mytharcher** [comment]
超赞干货！因材施教是真理，每个人的条件和耐受力都有很大差异。

根据我去年坚持一年慢跑的经验，一开始也没必要定很高的目标，我也就想每周跑个一次，每次五公里就够，重要的是通过运动保持一个较为良好的状态，以应对工作或生活中的其他压力。在低门槛的基础上就很容易坚持，通过一段时间形成习惯，之后就更容易保持。这样根据自己的状态来评估和安排，也不容易造成过度疲劳或者受伤。

另外社区里应该还有好几个健身达人：@gc87 @arlicle ，可以都来交流下哈！

**Comment by nanmu42** [comment]
66666666666

**Comment by ttop5** [comment]
体态纠正部分学到了，以后可以实践一下。

我之前在大学老师的引导下养成了夜跑的习惯，到现在断断续续也有个三四年的慢跑经历了，期间也参加过几次半马。全马本来打算19年开始参加的，然而18年下半年一直打游戏和其他原因跑步就荒废了。我之前夜跑的还是比较频繁的，一周四五次，每次大概五公里。期间也加入过别的项目（俯卧撑，仰卧起坐等）但都没坚持下来。跑步确实门槛最低，也最容易坚持，如果能找到一个小伙伴一起跑就更容易坚持了，而且我是户外跑，经常换换路线感觉也不会乏味。最近又是各种小病缠身，也肥了很多，19年怕是要再拾起来了233

**Comment by bigzhu** [comment]
你们都喜欢夜跑, 好厉害.

我是觉得跑步又累, 时间又长, 我这种懒人完全坚持不下来..

**Comment by williamwa** [comment]
最后这张照片gay值爆表🤔

**Comment by bigzhu** [comment]
那个是单身皮艇的防水包，不是那种小红包😂

无论如何，愿gay力与我们同在……

**Comment by nanmu42** [comment]
小红包？啥小红包？求科普。  :rofl:

**Comment by dotatata** [comment]
就看见"单身"俩字儿

**Comment by bigzhu** [comment]
@dotatata 准确说应该是"处男"
