### ISSUE TITLE
关于《开发团队的效率》与《我心目中的理想团队》两篇文章的讨论

### ISSUE THREAD

**Issue by ghost** [yncoder/yncoder.github.io#8]
第一篇是来自耗子哥：http://coolshell.cn/articles/11656.html
第二篇是玉伯在微信发的文章：http://mp.weixin.qq.com/s?__biz=MzAxNzM4OTE4Mg==&mid=210320484&idx=1&sn=eab0401c2a20b7d2fd117733807e1eed#rd

讨论的时候请尽量忽略当中互相抨击的部分……

以上！

**Comment by ghost** [comment]
开门见山：**我更喜欢玉伯**。

我觉得当我开始工作的时候，我的身份是工程师(而不是黑客)，我的职责是解决问题(而不是满足自己的代码欲望)。

然而在工程里肯定会有脏活要做，而且耗子只是说了个理想，没有路径，所以只能神往了。

**Comment by bigzhu** [comment]
我要来中庸了:
所有人都不喜欢和猪队友共事, 如果团队里面牛人和凡人差距太大,怎么共事? 这是玉伯没解决的问题.
耗子又太理想, 全栈牛人又不是咸鱼, 去哪里找那么多. 现在是凡人都招不到的时期.

不过总体来说我更赞同玉伯, 一群牛人, 那只能找个超人来将他们束成一个团队了.

团队里基本都比凡人厉害一些,但是没有特别冒尖的牛人.大家差距不大,但是都已经在往牛人迈进. 然后有一个牛人来做队长, 这样的团队应该会有超过平庸团队,但是又能持续很长时间的战斗力.

如何让团队怎么少写出臭代码, 队长你去操心吧.

**Comment by Vanessa219** [comment]
知乎上不是有了么。其实我觉得完全可以来社区讨论啊。 http://symphony.b3log.org/ :haircut:

**Comment by julycoolwind** [comment]
我觉得，要讨论这个问题，应该先明确目的。团队的结构是为目的服务的，目的不同，手段自然相异。就好比打仗一样，如果目的是完成一个有挑战性的战术任务，例如：敌后侦查、定点清除、破坏关键设施、刺杀等。以期达到四两拨千斤的效果。这种时候理想的结构都是各种大牛组成的一个战术小队，效果最理想。因为是小队、达到千斤的效果，相对与效果来说就可以负担较高的成本。但是如果想要赢得整个战争，就需要调动绝大多数的普通人发挥自己的能力。这个时候，就不可能为每个单兵在负担较高的成本，希望队伍里都是牛人从成本上来讲是不现实的。

记得一个国产抗战剧里有这样的情节，领导发现自己的队伍里有个神枪手，于是把他找来，希望他把自己的经验教和技巧交给别的展示，这样，可以组成一个都是神枪手的排、甚至连。这样的一个神枪排，哪威力可比大炮还牛。神枪手傻笑一下说“真正的神枪手都是天生的。”  大牛为啥被景仰，就是因为他的稀缺性。牛人永远都是少数，就算现在的人段数统统提高十级，大牛依然稀缺。因为牛人总会凭着自己的才智，高出平均水平几个数量级。

所以，我觉得现实的情况，还是需要弄清楚自己的目的，然后很衡量成本。为啥NBA的全明星队只是表演性质，没有哪个俱乐部由全明星组成。一方面是成本不可接受，一方面是都是牛人，团队成员之间本身就很难协调。

我觉得，现实里边只有尽可能的让团队中的每个人发挥自己的能力。更具自己团队的成长周期，在可能的情况下尽量优化团队的结构。如果有幸团队中有几个种子牛人，随着团队和团队牛人的成长，还要能够持续的留住这些人。有时候美梦成真也是噩梦。试想如果手下都是相当将军又有能力的兵。这个时候估计担心的不是手下没有牛人，而是手下的牛人都像自立山头，而团队不能及时提供这样的空间。那个时候不止是人才流失的问题，二十业务流失，外加竞争对手增加。

这些是我对团队一些杂乱的想法，欢迎讨论。
