### ISSUE TITLE
云南腾云信息产业公司招聘大数据工程师 （开发方向）

### ISSUE THREAD

**Issue by nanmu42** [yncoder/yncoder.github.io#80]
# 更新时间

2022年04月19日

# 内推投递通道

已关闭

# 公司介绍

腾云公司是为响应云南省“一部手机游云南”战略，由云南省政府和腾讯主导发起，腾讯公司、云南省投资控股集团、云南省交通投资建设集团三方共同成立（出资比例分别是：51:44:5），负责“一部手机游云南”项目的建设开发、平台运营等业务。

# 岗位职责

你会参与现有项目和新项目，和同事合作，负责掌握项目的数据流、控制流、技术架构、设施架构、部署方法、项目质量以及项目交付。你的工作会涵盖在线API服务和Spark任务的开发以及它们的质量控制。

# 我们希望你

* 具有本科或同等学历；
* 对软件工程、程序编写、任务交付有一定经验和理解；对时间空间复杂度有一定理解；具有解决问题和发现问题的能力；有一定内驱力，能够独立完成小规模任务；有良好的情商和沟通能力，能够与同事合作完成更大规模的任务；有一定自学和钻研能力，按项目需要学习新知识和技能。
* 熟悉Go/Java/Python至少一门语言，同时熟悉Spark, Flink至少一种数据处理方案，有落地项目经验。
* 熟悉SQL及至少一种数据库（PostgreSQL、Clickhouse、Elasticsearch）。
* 能够阅读英文文档。

# 下面是加分项

* 深入掌握在线API的开发，控制流和数据流门清，熟悉常见套路；
* 对数据敏感，能够发现异常或者兴趣点，对数据聚合维度和处理方式有自己的看法，有数据可视化能力；
* 有Github账号、开源项目或者技术博客，请在应聘资料中附上链接；
* 有机器学习/深度学习的经验。

# 你会获得

1. 氛围：友好有温度的氛围，我们尽力让工作有意思；
2. 工资：以你的当前工资为基点，根据评估和实际情况和你商量；
3. 福利：试用期不打折；每年额外1~3薪+项目奖金；
4. 五险一金：按工资全额缴纳；
5. 工作时间：朝九晚六，每周五天；
6. 年假，婚假：按云南省政策实施，婚假很长；
7. 这些不会少：年度体检，节假日礼品，自助茶水间。

**Comment by nanmu42** [comment]
# 秋季专场招聘会

腾云2019年秋季专场招聘会将于11月3日（本周日）上午9点在索菲特大酒店三楼云南厅举行。

欢迎Golang和有志转Golang的同学参加。

欢迎Java/前端/PHP/产品经理/运营/商务/采购/财务/市场的同学参加。

**Comment by nanmu42** [comment]
本招聘长期有效，Golang目前人才缺口很大，欢迎申请。

**Comment by nanmu42** [comment]
腾云秋季热招：Java/前端/PHP/Go/产品经理/运营/商务/采购/财务/市场，欢迎各位提交简历走内推。

点击[这里](https://github.com/nanmu42)，我的邮箱地址在头像下方，来邮请附上简历。

**Comment by ioalloc** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
