### ISSUE TITLE
如何加入组织？

### ISSUE THREAD

**Issue by qeesung** [yncoder/yncoder.github.io#81]
各位大佬，求带！

**Comment by siyushin** [comment]
这个组织很久没活动了吧。

**Comment by qeesung** [comment]
可惜了 😢

**Comment by mytharcher** [comment]
目前社区有两个在线交流的工具：

* 当前 issues 列表（非即时）
* 官方 QQ 群：39615502（即时）

相关使用方式可以看帖子 #54 里的介绍。

> 如何加入？

我的理解是两种方式，一是加入 QQ 群，直接申请就好，正常管理员都会通过。

二是在自己 GitHub 主页挂上 Yncoder 的徽标，这个管理员会邀请你们。

其他没有限制，任何人可以自发组织在此发起线下活动。
