### ISSUE TITLE
2020 年 1 月 4 日社区小聚会

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#83]
2019 马上就要过完，互联网有关寒冬的消息太多，不知道今年大家过的怎么样，所以就此攒个年末局大家一起来交流交流，轻松聊天为主，主题分享为辅，也是互相抱团取暖。

* **时间**：2020 年 1 月 4 日（周六）下午 14:00
* **地点**：云大（本部）创业园 1 楼咖啡厅

### 主题预订

1. 《去中心化金融的产品逻辑与技术实现》 by @ZhangRGK
2. 《[从远程工作到团队作战三年记](https://yanjunyi.com/blog/posts/remote-work-to-group-up)》 by @mytharcher

直接空降即可。

**Comment by bigzhu** [comment]
这个..我觉得需要来打破一下零回复.

创业园就是天桥那里对吧?

**Comment by williamwa** [comment]
下午见

**Comment by kentzhang-geek** [comment]
啥时候办下一次活动哦？我想分享一下北美offshore找工作加relocation加工作初体验，时间对得上的话我就zoom来了

**Comment by nanmu42** [comment]
好棒，期待。
