### ISSUE TITLE
国外远程工作机会列表

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#84]
电鸭社区最近发起的 [远程战疫 | 2020海外IT同行信息援助行动](https://eleduck.com/remote_anti_virus)，有一部分志愿者收集了很多国外远程工作的机会，有需要的朋友可以自取。

**Comment by siyushin** [comment]
@mytharcher 在社区里也是这个名字么？

**Comment by mytharcher** [comment]
@siyushin 是的哈。

**Comment by siyushin** [comment]
> @siyushin 是的哈。

有机会勾搭下。:)
