### ISSUE TITLE
支付宝-支付业务前端技术组招人啦

### ISSUE THREAD

**Issue by zhangtaii** [yncoder/yncoder.github.io#88]
- 工作地点: 杭州
- 联系邮箱: zhangtai.zt@alibaba-inc.com

### 团队介绍

我们是支付宝**前端技术部-支付业务前端技术组**，技术和业务双核心，同属**支付宝前端技术部**和**支付业务技术部。支付宝前端技术部**是蚂蚁集团前端技术顶梁柱，为蚂蚁集团提供全方位的技术解决方案(PC/H5研发体系、阿里系小程序体系等)**；支付业务技术部**团队多元化，我们与团队内资深的数据分析师和算法专家、客户端/服务端架构师、嵌入式专家、国内Top安全工程师、资深的产品和运营团队一起做国民应用，服务亿级用户，连接千万商家。

组内人才济济活动丰富：有50星王者的H5动效专家，有追求移动端极致体验的浮潜女神，有自主研发单片机JS OS的哈雷忠粉，有通读Linux内核源码的单板滑雪爱好者，还有一群动森er~，还有___的__(←给你留的位置，想加入这样的顶配团队，一起为世界带来微小而美好的变化吗？快投简历吧，机会稍纵即逝。)
 
### 职位描述

1. 负责支付宝最重要的支付相关业务(收银台/代扣/银行卡/亲密付/收付款码/资金/转账/账单/商家转账/手表支付/嵌入式支付...)服务亿级用户，连接千万商家；探索创新，推出爆款应用(我的家/抽奖/欧洲杯小程序/智造将来/宠物码/年度账单/存钱罐/亲子账户...)，面对最复杂场景，承接最大用户量，追求极致体验。
1. 参与应用框架体系建设以及前端工程体系建设，钻研各种前沿技术和创新交互，增强用户体验、开拓前端能力边界。
1. 深入理解业务，技术驱动产品发展，发挥你的创意和想象力，给用户带来全新的产品和体验。

### 职位要求

1. 两年及以上前端工作经验，熟练掌握移动端H5开发技术、熟悉移动端兼容特性，主导或独立负责过一定规模产品的前端研发，前端技术有代表性的专研领域。
1. 能提供完善的WebApp技术方案，能够沉淀并产出最佳实践，对JS引擎和CSS布局引擎有深入了解或工作经验者可加分；开发过有一定影响力的cli/vscode插件等工程化工具可加分。
1. 熟悉模块化、前端编译和构建原理，熟练掌握React/Vue等前端框架，深入理解其设计原理或阅读过相关源码。
1. 能够对项目做技术规划。拆分系统功能、模块，能够做功能分解，对现有系统的不足进行分析，找出问题推动解决，对新的应用有清晰合理的架构设计思路。
1. 在技术上有强烈的进取心，乐观坚韧，具有良好的沟通能力和团队合作精神、优秀的分析问题和解决问题的能力。

**Comment by mytharcher** [comment]
还以为是昆明有远程职位啊。
