### ISSUE TITLE
难得的高大上活动（免费）：AWSOME DAY 昆明站（2020 年 11 月 10 日 全天）

### ISSUE THREAD

**Issue by mytharcher** [yncoder/yncoder.github.io#94]
亚马逊 AWS 云贵区业务总监 Junwei 联系到我们，得知 11 月 10 日 AWS 有在昆明准备做一场 AWSOME DAY 的活动。个人感觉昆明这样技术相关高大上的会议是非常难得了，对运维和最新云计算技术感兴趣的开发者朋友们可以报名参与了！

从活动方得到的信息是：

> * 本次活动**完全免费**！
> * 而且一整天的活动有礼品，有教材，含酒店午餐，还可以抽奖（kindle）！
> * 爱学习的同学现场学完还会有 AWSOME DAY 的培训认证。
> 
> 需要扫码提前注册， 到场了会做注册验证，凭参会牌获取以上资格。

部分讲师：

* [费良宏](https://www.baidu.com/s?wd=%E8%B4%B9%E8%89%AF%E5%AE%8F)：现任亚马逊AWS首席云计算技术顾问，开发者布道师
* 李沐：亚马逊 AI 首席科学家（发明 MXNet 机器学习框架）

详细信息见海报：

![WechatIMG17](https://user-images.githubusercontent.com/525658/96549944-c4499e80-12e2-11eb-861f-06e595079a82.jpeg)

**Comment by nanmu42** [comment]
太难得了，在工作日，可惜了。

**Comment by yxyufo110** [comment]
周二,gg
