### ISSUE TITLE
弥勒品元园艺有限公司招聘 CTO / 程序员

### ISSUE THREAD

**Issue by bigzhu** [yncoder/yncoder.github.io#95]
## 公司介绍

国内规模及技术排第一的鲜切花企业, 偏向物联网企业. 公司大量使用先进自动化种植系统, 基本实现机器自动控制生产, 公司内设立了切花玫瑰唯一一个专家院士工作站.

年收入 4000 万以上, 公司人数 100+

![image](https://user-images.githubusercontent.com/489815/98770767-f18af780-241d-11eb-9c74-4c68f9f4cd55.png)

![image](https://user-images.githubusercontent.com/489815/98770786-fcde2300-241d-11eb-98a5-d96d2f1c35b2.png)

![image](https://user-images.githubusercontent.com/489815/98770806-02d40400-241e-11eb-9b5d-d3911862efb5.png)

### CTO

负责组织管理团队, 构建技术架构.

希望寻找有创业冲动, 愿意入行花卉行业, 愿意深入了解行业知识的人, 一年合作后可考虑转为合伙人.

待遇: 2w

### 程序员

立志种花的程序员, 有一些经验, 能做独立开发.

待遇: 1w

### 公司内部系统

整合经营分析, oa, 财务, 人力, 仓储的服务公司内部管理的综合管理系统. 需要与公司目前现有自动化生产流程逐步整合迭代, 最终实现为一个大的行业管理系统.

### 销售系统

销售流程中需要使用到的系统, 包括对内接入整合, 对外展示. 需要前端,后端, APP 都会涉及到. 类似旺店通

### 管理人员及团队

目前有两名程序员.

老板硕士学历, 二十年前也是程序员, 心态开放, 善于接受新事物, 所以才能打造最自动化, 最先进的鲜切花企业.

公司 100+ 人, 其他应该是一些行业或者种花的人.

![image](https://user-images.githubusercontent.com/489815/98770837-12ebe380-241e-11eb-8286-6e611790f830.png)

## bigzhu 考虑

老板思维先进, 且以前当过程序员, 沟通会相对顺畅, 不好的地方是不好忽悠其也容易低估程序工作量.

公司在弥勒, 适合单身且创业激情充沛的程序员, 后续有考虑迁移到昆明, 但是也是几年以后的事了.

公司并没有成熟的 IT 团队和技术价格, 可以说这块刚起步, 是好事也是坏事, 这时进入自由度比较大. 老板有做到上市的野心, 在云南这个鲜切花世界领先的地方也不是不可能, 有机遇, 可以抱着创业的心态和老板一起试试.

开发系统属于公司和行业内部系统, 鲜切花也是属于蓬勃发展的朝阳行业且是云南支柱产业, 愿意跨行业深入了解这块行业来整合 IT 的人, 那这是一个很好的成为行业 IT 领头人的机会. 如果只愿意做单纯 IT 或者偏互联网, 那么并不是很合适.

私人公司, 可能有些不够规范或者变数很大的地方.

有意向的朋友可以给我投简历, 由我来直接内推给老板会好很多. 或者加我微信来了解更多的公司信息.

- 邮箱: vermiliondun@gmail.com
- 微信: bigzhu

**Comment by StevenSKing** [comment]
牛批！早来两个月招人我就去了~哈哈哈哈

**Comment by YongHangPu** [comment]
6
