### ISSUE TITLE
杭州映云科技公司（EMQ）招聘前端开发工程师

### ISSUE THREAD

**Issue by ysfscream** [yncoder/yncoder.github.io#97]
## 关于 EMQ

[EMQ - 杭州映云科技](https://www.emqx.cn) 是一家开源软件公司，专注于 5G 和物联网领域的消息与流处理软件，面向全球运营。

EMQ 总部位于杭州，在北京、上海、硅谷、法兰克福设有分支机构，核心产品包括面向云和边缘计算的 IoT 消息中间件以及轻量级流式处理中间件，累计已服务全球 5000+ 企业用户，并与数十家世界 500 强企业达成战略合作，典型用户包括 HPE、VMware、Verifone、Ericsson、华为、中国电信、中国移动、国家电网、上汽大众等。

EMQ 发起与运营的开源 [物联网 MQTT 服务器](https://www.emqx.io/cn/products/broker)，Github Star 数量在同类型项目中排名第一，是国内在开源领域具有全球影响力的项目之一。

最近 EMQ 完成由高瓴创投领投、GGV 跟投的近 1.5 亿元 B 轮融资。
https://www.emqx.cn/news/emq-completes-series-b-funding-round

EMQ 官网：http://www.emqx.cn

EMQ X 开源项目： https://github.com/emqx/emqx

Base: 昆明，杭州，北京等。

招聘职位
----------

#### 基本要求

1. 熟悉 JavaScript、TypeScript 和新语言规范和语法特性，如 ES2015 等；
2. 对主流前端框架（ React \ Vue \ Angular 等）至少一种有深入应用并深入理解其设计原理；
3. 熟悉 Webpack 构建，Node 脚本开发和常用 Prettier、ESLint、Babel 等配置；
4. 在使用浏览器 API 和优化前端性能方面有丰富经验；
5. 熟悉 Electron 跨平台开发，并了解其实现原理；
6. 熟悉计算机基础（操作系统，网络，数据库，算法，编译原理等）。

#### 加分项

1. 注重产品质量，具有良好的代码风格、接口设计与程序架构；
2. 关注业界发展，对最新的前端技术有浓厚的兴趣及独特的见解，关注前端前沿技术研究，通过新技术服务团队和业务；
3. 参与过大型互联网产品的设计和研发工作，整体负责过一个线上系统的技术选型、规划与开发，能独立完成复杂前端系统或大型框架设计；
4. 热爱开源，拥抱开源，有自己的开源项目或是开源项目的核心贡献者；
5. 对函数式编程有一定的了解和兴趣。

#### 工作内容

1. 负责 EMQ 相关开源产品的前端开发工作；
2. 负责推动与优化已有前端项目的基础架构与组件抽象；
3. 与团队配合完成整体项目规划、设计与开发；
4. 参与 [MQTT 5.0 物联网云服务平台](https://cloud.emqx.io/cn/) 的前端开发工作；
5. 参与 [MQTT X - 跨平台 MQTT 5.0 桌面客户端工具](https://mqttx.app/cn/) 的开发工作。

#### 薪资待遇

基础 15k ~ 35k (优秀者可面议)

标配最新款 Macbook Pro + DELL 4K 显示器

无限零食和饮料

舒适轻松的办公环境

最具 GEEK 氛围的工作环境

自由开放的团建活动

各种节假日福利

...

### 更多职位，可访问 [拉钩](https://www.lagou.com/gongsi/j157269.html) 查看

团队价值观
----------

热爱开源，拥抱开源。

联系方式
----------

* 联系人：ysfscream
* 邮件：yusf at emqx.io

**Comment by ttop5** [comment]
🙋‍♂️

**Comment by asuka730** [comment]
🚀 🚀

**Comment by ysfscream** [comment]
Hi, all! 招聘信息更新了一下😂 年前年后都持续招聘呀！

**Comment by CrazyWisdom** [comment]
🚀 🚀🚀 🚀🚀 🚀

**Comment by YongHangPu** [comment]
爱了
